export const COSRENT_LIST = [
  {
    nama: 'Rental Costume Jingliu',
    series: 'Honkai: Star Rail',
    costume: 'Jingliu',
    brand: 'Wudu',
    rental: 'Fuku.cosrent',
    instagram: 'fuku.cosrent',
    harga: 'Rp 120.000 / 3 hari',
    size: 'M',
    gender: '-',
    ld: '82-86 cm',
    lp: '67-70 cm',
    lokasi: 'Kabupaten Cilacap, Jawa Tengah',
    detail: 'Rental kostum Jingliu - Honkai: Star Rail di Kabupaten Cilacap - Jawa Tengah brand Wudu ukuran M harga Rp 120.000 / 3 hari',
    image: 'https://ruangcosplay.com/images/post/919/8866/lg/dEpzOJQlInaLXLRL8InU.webp',
    link: 'https://ruangcosplay.com/sewa/jingliu/8866'
  },
  {
    nama: 'May Rabbit Cos Main Character (MC) (Love and Deepspace ) Cosplay Costume Set - Love And Deepspace (Size L)',
    series: 'Love and Deepspace',
    costume: 'MC • Hunter Uniform',
    brand: 'May Rabbit Cos',
    rental: 'Kyou Cosplay Corner',
    instagram: 'kyoucosplaycorner',
    harga: 'Rp 120.000 / 3 hari',
    size: 'L',
    gender: '-',
    ld: '90-94 cm',
    lp: '73-77 cm',
    lokasi: 'Tangerang Selatan, Banten',
    detail: 'Kyou Cosplay Corner CatalogueLove and Deepspace - MC (L)Costume brand : May Rabbit Cos👘Include :Fullset costumeAccessoriesWig🧺 Laundry : + 20K',
    image: 'https://ruangcosplay.com/images/post/3709/21933/lg/cwrvDK0K3xoxmoIOVMLi.webp',
    link: 'https://ruangcosplay.com/sewa/mc-love-deepspace/21933'
  },
  {
    nama: 'Rental Kostum Shizuku Tan/ Shizuku Kuroe',
    series: 'My Dress Up Darling',
    costume: 'Shizuku Tan',
    brand: 'Maker Lokal',
    rental: 'Plue_rentcos',
    instagram: 'plue_rentcos',
    harga: 'Rp 95.000 / 3 hari',
    size: 'S - M',
    gender: 'Wanita',
    ld: '-',
    lp: '-',
    lokasi: 'Kabupaten Semarang, Jawa Tengah',
    detail: 'Rental kostum Shizuku Tan - My Dress Up Darling di Kabupaten Semarang - Jawa Tengah Maker Lokal ukuran S - M harga Rp 95.000 / 3 hari',
    image: 'https://ruangcosplay.com/images/post/2036/15598/lg/QLC7UTQb2uiRSpJxKwqI.webp',
    link: 'https://ruangcosplay.com/sewa/shizuku-tan/15598'
  },
  {
    nama: 'Rafayel God Of The Tides',
    series: 'Love and Deepspace',
    costume: 'Rafayel',
    brand: 'Manzhiying',
    rental: 'Haney Cosrent',
    instagram: 'haney.cosrent',
    harga: 'Rp 250.000 / 3 hari',
    size: 'XXL',
    gender: '-',
    ld: '100-110 cm',
    lp: '80-90 cm',
    lokasi: 'Bandung, Jawa Barat',
    detail: '♡ READY TO RENT ♡RafayelLove & DeepspaceGod Of The Tides250k / 3 daysCostum Only : 230k / 3 days ‼️ SELECTIVE RENT ‼️CEK SNK TAMBAHAN DI FOTO▫️ Wig Brand Manmei atau Brand Songtaste(Bisa pilih selama masih avail)Kostum Brand ManZhiYi Size 2XLLD 100-110cmLP 80-90cm▫️ Manset Tato▫️ Celana▫️ Outer Celana▫️ Obi + Acc ▫️ Selendang▫️ Kalung▫️ Gelang▫️ Acc TulangSIZE PAXEL : ❤️ Kostum : Large + WAJIB ASURANSI❤ Wig + Kostum : Large + WAJIB ASURANSI❗ TIDAK ADA BIAYA LAUNDRY JIKA KOSTUM KEMBALI TANPA NODA❗Kostum yang kembali dengan noda akan dikenakan denda tergantung seberapa membandel nodanya. Cek postingan \'DENDA\' untuk perkiraan harganya.#rafayelcosplay #rentalkostum #rentalcosplay #rentalkostumbandung #rentalkostumcosplay',
    image: 'https://ruangcosplay.com/images/post/51/15883/lg/QIwFn8cIXrM7F1D3pARi.webp',
    link: 'https://ruangcosplay.com/sewa/rafayel/15883'
  },
  {
    nama: 'Hatsune Miku - Symphony 2019',
    series: 'Vocaloid',
    costume: 'Hatsune Miku',
    brand: 'No Brand / Freebrand',
    rental: 'Chungiie Cosplay Rent',
    instagram: 'chungiie.cos',
    harga: 'Rp 120.000 / 3 hari',
    size: 'S',
    gender: 'Wanita',
    ld: '-',
    lp: '-',
    lokasi: 'Bekasi, Jawa Barat',
    detail: '[ READY ✅ ]VocaloidCharacter : Hatsune Miku - Symphony 2019Size SPrice : 120K / 3 Days',
    image: 'https://ruangcosplay.com/images/post/2853/16738/lg/7Kb2C6HyHyXQ3U7niVYc.webp',
    link: 'https://ruangcosplay.com/sewa/hatsune-miku/16738'
  },
  {
    nama: 'Tomoyo daidouji',
    series: 'Cardcaptor Sakura',
    costume: 'Tomoyo Daidouji',
    brand: 'Maker Lokal',
    rental: 'Rental bekasi',
    instagram: 'Elementary_rentcos',
    harga: 'Rp 75.000 / 3 hari',
    size: 'M - L',
    gender: 'Wanita',
    ld: '-',
    lp: '-',
    lokasi: 'Bekasi, Jawa Barat',
    detail: '•> wig •> kostum',
    image: 'https://ruangcosplay.com/images/post/440/16732/lg/qpv2V6AA3rs5344FB0fk.webp',
    link: 'https://ruangcosplay.com/sewa/tomoyo-daidouji/16732'
  },
  {
    nama: 'Lumine Halloween',
    series: 'Genshin Impact',
    costume: 'Lumine',
    brand: 'Wudu',
    rental: 'Miku Rents',
    instagram: 'mikurents',
    harga: 'Rp 100.000 / 3 hari',
    size: 'M',
    gender: '-',
    ld: '85-88 cm',
    lp: '64-67 cm',
    lokasi: 'Semarang, Jawa Tengah',
    detail: 'Include:WigCostumeACC (pita, topi, ACC kepala, ACC rok, ACC topi, sarung tangan panjang dan pendek)Exclude:Bra strap — 5k/3 Days (disarankan untuk tidak punya bra strap)',
    image: 'https://ruangcosplay.com/images/post/445/13672/lg/P1GXHsFv46QrxbtS5i0R.webp',
    link: 'https://ruangcosplay.com/sewa/lumine/13672'
  },
  {
    nama: 'Krul Tepes',
    series: 'Owari no Seraph',
    costume: 'Krul Tepes',
    brand: 'Wudu',
    rental: 'Zyuu_rentcoss',
    instagram: 'zyuu_rentcoss',
    harga: 'Rp 125.000 / 3 hari',
    size: '-',
    gender: 'Wanita',
    ld: '-',
    lp: '-',
    lokasi: 'Pekanbaru, Riau',
    detail: 'Ready pertengahan desember 2025Free laundrySize XS fit to S',
    image: 'https://ruangcosplay.com/images/post/2322/15885/lg/dBV0k7ulMoyKOM8k167W.webp',
    link: 'https://ruangcosplay.com/sewa/krul-tepes/15885'
  },
  {
    nama: 'MC Dreamy Heart — Love and Deepspace (LADS)',
    series: 'Love and Deepspace',
    costume: 'MC • Dreamy Heart',
    brand: 'HSIU',
    rental: 'Renelle Cosrent',
    instagram: 'renelle.cosrent',
    harga: 'Rp 75.000 / 3 hari',
    size: 'M',
    gender: '-',
    ld: '92 cm',
    lp: '68 cm',
    lokasi: 'Solo, Jawa Tengah',
    detail: '𐙚 𝑟𝑒𝑎𝑑𝑦 𝑓𝑜𝑟 𝑟𝑒𝑛𝑡 𓂃 ࣪˖ ִֶָ𐀔𓍢ִ໋🌷͙֒♡ mc dreamy heart (rafayel bday) ㅡ love and deepspace ౨ৎ✓ first time 🅞🅚✘ no crossdress ✘★ 75k / 3 days↳ cek pinned post buat jadwal pengiriman ;) ★ BRAND↳ HSIU ★ SIZE Ⓜ️↳ LD & LP pada katalog berdasarkan size chart dari brand HSIU ★ ADDITIONAL↳ rent = wig (katalog terpisah)↳ buy = wig cap +7k ★ WEIGHT↳ 1 kg | Small (without wig) ★ silakan DM jika ada yang ingin ditanyakan (◡‿◡✿) ‼️pastikan akun kamu udah memenuhi syarattt🫨 #mclads #lads #mccosplay #ladscosplay #rentalmc #rentalmclads #rentallads #rentalloveanddeepspace #rentalcosplaysolo #rentalcosplayjateng #rentalcostume #rentalcosplay #cosrent',
    image: 'https://ruangcosplay.com/images/post/286/15188/lg/C6mz1KMCNM8GjVuD6RgP.webp',
    link: 'https://ruangcosplay.com/sewa/mc-dreamy-heart/15188'
  },
  {
    nama: 'RENTAL COSTUME BAILI XUANCE BOOMERANG ACE SKIN',
    series: 'Honor of Kings',
    costume: 'Xuance',
    brand: 'Maker Lokal',
    rental: 'Medh ♡ Leon suamiku Kennedy',
    instagram: 'meichi.rentcos',
    harga: 'Rp 110.000 / 3 hari',
    size: 'L',
    gender: 'Pria',
    ld: '-',
    lp: '-',
    lokasi: 'Kabupaten Sumedang, Jawa Barat',
    detail: 'Rental kostum Xuance - Honor of Kings di Kabupaten Sumedang - Jawa Barat Maker Lokal ukuran L harga Rp 110.000 / 3 hari',
    image: 'https://ruangcosplay.com/images/post/2624/21930/lg/K8OjmjJRkWMPPqXtprba.webp',
    link: 'https://ruangcosplay.com/sewa/xuance/21930'
  },
]

export default COSRENT_LIST
