export const MOUNT_COOLDOWN = 5 * 60 * 60 * 1000
export const MOUNT_PREMIUM_COOLDOWN = 2 * 60 * 60 * 1000
export const MOUNT_TEAM_LIMIT = 5

export const MOUNTAINS = [
  { name: 'Gunung Kabut', height: 950, type: 'Fiksi', difficulty: 'Mudah' },
  { name: 'Puncak Senja', height: 1250, type: 'Fiksi', difficulty: 'Mudah' },
  { name: 'Gunung Pulosari', height: 1346, type: 'Nyata', difficulty: 'Mudah' },
  { name: 'Mount Pinatubo', height: 1486, type: 'Nyata', difficulty: 'Mudah' },
  { name: 'Mount Aso', height: 1592, type: 'Nyata', difficulty: 'Mudah' },
  { name: 'Gunung Kelimutu', height: 1639, type: 'Nyata', difficulty: 'Mudah' },
  { name: 'Gunung Batur', height: 1717, type: 'Nyata', difficulty: 'Mudah' },
  { name: 'Gunung Andong', height: 1726, type: 'Nyata', difficulty: 'Mudah' },
  { name: 'Steep Steps', height: 1800, type: 'Fiksi', difficulty: 'Mudah' },
  { name: 'Gunung Awan', height: 1900, type: 'Fiksi', difficulty: 'Mudah' },
  { name: 'Mount Talinis', height: 1903, type: 'Nyata', difficulty: 'Mudah' },
  { name: 'Mount Washington', height: 1917, type: 'Nyata', difficulty: 'Mudah' },
  { name: 'Mount Tongariro', height: 1978, type: 'Nyata', difficulty: 'Mudah' },
  { name: 'Mount Hanami', height: 2000, type: 'Fiksi', difficulty: 'Mudah' },
  { name: 'Mount Jawa', height: 2050, type: 'Fiksi', difficulty: 'Mudah' },
  { name: 'Gunung Tangkuban Perahu', height: 2084, type: 'Nyata', difficulty: 'Mudah' },
  { name: 'Mount Papua', height: 2100, type: 'Fiksi', difficulty: 'Mudah' },
  { name: 'Mount Banahaw', height: 2170, type: 'Nyata', difficulty: 'Mudah' },
  { name: 'Snowy Cliffs', height: 2200, type: 'Fiksi', difficulty: 'Mudah' },
  { name: 'Gunung Salak', height: 2211, type: 'Nyata', difficulty: 'Mudah' },
  { name: 'Gunung Sibayak', height: 2212, type: 'Nyata', difficulty: 'Mudah' },
  { name: 'Mount Kosciuszko', height: 2228, type: 'Nyata', difficulty: 'Mudah' },
  { name: 'Mount Aventura Classic', height: 2250, type: 'Fiksi', difficulty: 'Mudah' },
  { name: 'Mount Aventura', height: 2250, type: 'Fiksi', difficulty: 'Mudah' },
  { name: 'Gunung Bromo', height: 2329, type: 'Nyata', difficulty: 'Mudah' },
  { name: 'Climbing Simulator Mountain', height: 2400, type: 'Fiksi', difficulty: 'Mudah' },
  { name: 'Gunung Patuha', height: 2434, type: 'Nyata', difficulty: 'Mudah' },
  { name: 'Mount Mayon', height: 2462, type: 'Nyata', difficulty: 'Mudah' },
  { name: 'Mount Hanami Adventure', height: 2500, type: 'Fiksi', difficulty: 'Menengah' },
  { name: 'Mount Uludağ', height: 2543, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Gunung Prau', height: 2565, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Gunung Talang', height: 2597, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Treacherous Tower', height: 2600, type: 'Fiksi', difficulty: 'Menengah' },
  { name: 'Gunung Papandayan', height: 2665, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Obby Mountain', height: 2700, type: 'Fiksi', difficulty: 'Menengah' },
  { name: 'Mount Ruapehu', height: 2797, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Gunung Ijen', height: 2799, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Mount Hermon', height: 2814, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Gunung Cikuray', height: 2821, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Gunung Tambora', height: 2850, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Gunung Singgalang', height: 2877, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Gunung Marapi', height: 2891, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Gunung Merapi', height: 2910, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Mount Merapi Adventure', height: 2910, type: 'Fiksi', difficulty: 'Menengah' },
  { name: 'Mount Merapi Climb Simulator', height: 2910, type: 'Fiksi', difficulty: 'Menengah' },
  { name: 'Mount Olympus (Greece)', height: 2918, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Mount Apo', height: 2954, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Gunung Gede', height: 2958, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Mount Gede via Gunung Putri', height: 2958, type: 'Fiksi', difficulty: 'Menengah' },
  { name: 'Zugspitze', height: 2962, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Mount of Gods', height: 3000, type: 'Fiksi', difficulty: 'Menengah' },
  { name: 'Mount Jawa Adventure', height: 3000, type: 'Fiksi', difficulty: 'Sulit' },
  { name: 'Gunung Jawa Adventure', height: 3000, type: 'Fiksi', difficulty: 'Sulit' },
  { name: 'Mount Tateyama', height: 3015, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Gunung Agung', height: 3031, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Mount Aspiring / Tititea', height: 3033, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Gunung Ciremai', height: 3078, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Mount Ciremai Adventure', height: 3078, type: 'Fiksi', difficulty: 'Sulit' },
  { name: 'Gunung Argopuro', height: 3088, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Mount Lebanon', height: 3088, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Gunung Merbabu', height: 3145, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Mount Merbabu Adventure', height: 3145, type: 'Fiksi', difficulty: 'Menengah' },
  { name: 'Gunung Sindoro', height: 3153, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Gunung Dempo', height: 3173, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Mount Hotaka', height: 3190, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Gunung Lawu', height: 3265, type: 'Nyata', difficulty: 'Menengah' },
  { name: 'Mount Etna', height: 3329, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Gunung Raung', height: 3332, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Gunung Arjuno', height: 3339, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Gunung Sumbing', height: 3371, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Fitz Roy', height: 3405, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Gunung Slamet', height: 3428, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Mount Hood', height: 3429, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Gunung Latimojong', height: 3478, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Vertical Ascension', height: 3500, type: 'Fiksi', difficulty: 'Sulit' },
  { name: 'Mount Semeru', height: 3676, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Mount Semeru Adventure', height: 3676, type: 'Fiksi', difficulty: 'Sulit' },
  { name: 'Mount Semeru Expedition', height: 3676, type: 'Fiksi', difficulty: 'Sulit' },
  { name: 'Mount Teide', height: 3715, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Aoraki / Mount Cook', height: 3724, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Mount Rinjani', height: 3726, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Mount Fuji', height: 3776, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Grossglockner', height: 3798, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Gunung Kerinci', height: 3805, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Mount Erciyes', height: 3917, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Mount Kinabalu', height: 4095, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Jebel Toubkal', height: 4167, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Mauna Loa', height: 4169, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Mauna Kea', height: 4207, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Mount Elgon', height: 4321, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mount Shasta', height: 4322, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mount Rainier', height: 4392, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mount Elbert', height: 4401, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mount Whitney', height: 4421, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Matterhorn', height: 4478, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Puncak Aether', height: 4500, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Ras Dashen', height: 4550, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mount Meru', height: 4566, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mont Blanc', height: 4808, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mount Baker', height: 3286, type: 'Nyata', difficulty: 'Sulit' },
  { name: 'Mount Baker (Uganda)', height: 4844, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Puncak Jaya', height: 4884, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mount Papua Summit', height: 4884, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Mount Speke', height: 4890, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mount Vinson', height: 4892, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mount of Gods Summit', height: 5000, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Mount Kazbek', height: 5054, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mount Stanley', height: 5109, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mount Ararat', height: 5137, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mount Kenya', height: 5199, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Iztaccíhuatl', height: 5230, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Popocatépetl', height: 5426, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mount Damavand', height: 5610, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Pico de Orizaba', height: 5636, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mount Elbrus', height: 5642, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Antisana', height: 5704, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Cayambe', height: 5790, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mount Kilimanjaro', height: 5895, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Cotopaxi', height: 5897, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Alpamayo', height: 5947, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mount Logan', height: 5959, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Puncak Aurora', height: 6100, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Denali', height: 6190, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Chimborazo', height: 6263, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Salkantay', height: 6271, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Illimani', height: 6438, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Mera Peak', height: 6476, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Sajama', height: 6542, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Tupungato', height: 6570, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Llullaillaco', height: 6739, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Tres Cruces', height: 6748, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Huascarán', height: 6768, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Pissis', height: 6793, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Ama Dablam', height: 6812, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Ojos del Salado', height: 6893, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Aconcagua', height: 6961, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Khan Tengri', height: 7010, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Kangto', height: 7090, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Puncak Zenith', height: 7100, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Trisul I', height: 7120, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Baruntse', height: 7129, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Nun Kun', height: 7135, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Chaukhamba I', height: 7138, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Jengish Chokusu', height: 7439, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Noshaq', height: 7492, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Ismoil Somoni Peak', height: 7495, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Annapurna IV', height: 7525, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Muztagh Ata', height: 7546, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Annapurna III', height: 7555, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Minya Konka', height: 7556, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Gangkhar Puensum', height: 7570, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Kongur Tagh', height: 7649, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Saser Kangri I', height: 7672, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Tirich Mir', height: 7708, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Jannu', height: 7710, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Saltoro Kangri', height: 7742, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Kamet', height: 7756, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Rakaposhi', height: 7788, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Puncak Celestia', height: 7800, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Nanda Devi', height: 7816, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Annapurna II', height: 7937, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Gasherbrum III', height: 7946, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Gyachung Kang', height: 7952, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Shishapangma', height: 8027, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Gasherbrum II', height: 8035, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Broad Peak', height: 8051, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Gasherbrum I', height: 8080, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Annapurna I', height: 8091, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Nanga Parbat', height: 8126, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Manaslu', height: 8163, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Dhaulagiri I', height: 8167, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Cho Oyu', height: 8188, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Makalu', height: 8485, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Lhotse', height: 8516, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Kangchenjunga', height: 8586, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'K2', height: 8611, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Puncak Titan', height: 8700, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Mount Everest', height: 8849, type: 'Nyata', difficulty: 'Ekstrem' },
  { name: 'Gunung Petir', height: 9000, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Puncak Nirwana', height: 9200, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Gunung Astralis', height: 9400, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Puncak Ragnarok', height: 9600, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Gunung Elysium', height: 9800, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Puncak Infinity', height: 10000, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Gunung Arunika', height: 10300, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Puncak Valhalla', height: 10600, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Gunung Solaris', height: 10900, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Puncak Olympus', height: 11200, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Gunung Zenith', height: 11500, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Puncak Eternity', height: 11800, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Gunung Divinity', height: 12000, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Puncak Absolute', height: 12500, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Gunung Transcend', height: 13000, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Puncak Infinity Prime', height: 13500, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Mount Mantan', height: 1200, type: 'Fiksi', difficulty: 'Sulit' },
{ name: 'Mount Anime', height: 2500, type: 'Fiksi', difficulty: 'Ekstrem' },
{ name: 'Mount Cyberpunk', height: 4200, type: 'Fiksi', difficulty: 'Ekstrem' },
{ name: 'Mount GTA', height: 3100, type: 'Fiksi', difficulty: 'Sulit' },
{ name: 'Mount Minecraft', height: 2800, type: 'Fiksi', difficulty: 'Sulit' },
{ name: 'Mount Roblox', height: 3500, type: 'Fiksi', difficulty: 'Ekstrem' },
{ name: 'Mount Terraria', height: 2200, type: 'Fiksi', difficulty: 'Sulit' },
{ name: 'Mount Elden', height: 6800, type: 'Fiksi', difficulty: 'Ekstrem' },
{ name: 'Mount Skyrim', height: 5400, type: 'Fiksi', difficulty: 'Ekstrem' },
{ name: 'Mount Hyrule', height: 3900, type: 'Fiksi', difficulty: 'Sulit' },
{ name: 'Mount Pokémon', height: 1800, type: 'Fiksi', difficulty: 'Sedang' },
{ name: 'Mount One Piece', height: 4600, type: 'Fiksi', difficulty: 'Ekstrem' },
{ name: 'Mount Shinobi', height: 3200, type: 'Fiksi', difficulty: 'Sulit' },
{ name: 'Mount Saiyan', height: 7500, type: 'Fiksi', difficulty: 'Ekstrem' },
{ name: 'Mount Titan', height: 6200, type: 'Fiksi', difficulty: 'Ekstrem' },
{ name: 'Mount Demon', height: 5000, type: 'Fiksi', difficulty: 'Ekstrem' },
{ name: 'Mount Waifu', height: 900, type: 'Fiksi', difficulty: 'Mudah' },
{ name: 'Mount Husbu', height: 950, type: 'Fiksi', difficulty: 'Mudah' },

{ name: 'Mount Broken Heart', height: 1600, type: 'Fiksi', difficulty: 'Sedang' },
{ name: 'Mount Friendzone', height: 1900, type: 'Fiksi', difficulty: 'Sedang' },
{ name: 'Mount Red Flag', height: 2300, type: 'Fiksi', difficulty: 'Sulit' },
{ name: 'Mount Green Flag', height: 2100, type: 'Fiksi', difficulty: 'Sedang' },
{ name: 'Mount Mantan Terakhir', height: 2700, type: 'Fiksi', difficulty: 'Sulit' },
{ name: 'Mount Move On', height: 3300, type: 'Fiksi', difficulty: 'Sulit' },
{ name: 'Mount Kenangan', height: 2900, type: 'Fiksi', difficulty: 'Sulit' },
{ name: 'Mount Ghosting', height: 3700, type: 'Fiksi', difficulty: 'Ekstrem' },
{ name: 'Mount Overthinking', height: 4100, type: 'Fiksi', difficulty: 'Ekstrem' },
{ name: 'Mount Deadline', height: 4400, type: 'Fiksi', difficulty: 'Ekstrem' },
{ name: 'Mount Skripsi', height: 5100, type: 'Fiksi', difficulty: 'Ekstrem' },
{ name: 'Mount Kerja', height: 3600, type: 'Fiksi', difficulty: 'Sulit' },
{ name: 'Mount Gajian', height: 1000, type: 'Fiksi', difficulty: 'Mudah' },

{ name: 'Mount Internet', height: 3000, type: 'Fiksi', difficulty: 'Sulit' },
{ name: 'Mount Dark Web', height: 5700, type: 'Fiksi', difficulty: 'Ekstrem' },
{ name: 'Mount Server', height: 3400, type: 'Fiksi', difficulty: 'Sulit' },
{ name: 'Mount Glitch', height: 4700, type: 'Fiksi', difficulty: 'Ekstrem' },
{ name: 'Mount Error 404', height: 4040, type: 'Fiksi', difficulty: 'Sulit' },
{ name: 'Mount Loading', height: 1500, type: 'Fiksi', difficulty: 'Sedang' },
{ name: 'Mount Lag', height: 2000, type: 'Fiksi', difficulty: 'Sedang' },
{ name: 'Mount Ping 999', height: 5900, type: 'Fiksi', difficulty: 'Ekstrem' },
{ name: 'Mount AI', height: 6300, type: 'Fiksi', difficulty: 'Ekstrem' },
{ name: 'Mount Digital', height: 3800, type: 'Fiksi', difficulty: 'Sulit' },
{ name: 'Mount Neon', height: 2800, type: 'Fiksi', difficulty: 'Sulit' },

{ name: 'Mount Apocalypse', height: 8000, type: 'Fiksi', difficulty: 'Ekstrem' },
  { name: 'Mount Olympus Mons', height: 21229, type: 'Nyata', difficulty: 'Ekstrem' }
].sort((a, b) => a.height - b.height)

export const MOUNT_TRASH = [
  { id: 'botol_air_mineral', name: 'Botol air mineral', emoji: '🧴', price: 150 },
  { id: 'botol_minuman', name: 'Botol minuman', emoji: '🧴', price: 150 },
  { id: 'kaleng_minuman', name: 'Kaleng minuman', emoji: '🥫', price: 200 },
  { id: 'gelas_plastik', name: 'Gelas plastik', emoji: '🥤', price: 100 },
  { id: 'sedotan_plastik', name: 'Sedotan plastik', emoji: '🥤', price: 50 },
  { id: 'tutup_botol', name: 'Tutup botol', emoji: '🔘', price: 50 },
  { id: 'bungkus_mie_instans', name: 'Bungkus mie instan', emoji: '🍜', price: 100 },
  { id: 'bungkus_snack', name: 'Bungkus snack', emoji: '🍿', price: 100 },
  { id: 'bungkus_roti', name: 'Bungkus roti', emoji: '🍞', price: 75 },
  { id: 'bungkus_biskuit', name: 'Bungkus biskuit', emoji: '🍪', price: 75 },
  { id: 'bungkus_cokelat', name: 'Bungkus cokelat', emoji: '🍫', price: 75 },
  { id: 'bungkus_permen', name: 'Bungkus permen', emoji: '🍬', price: 50 },
  { id: 'bungkus_kopi', name: 'Bungkus kopi', emoji: '☕', price: 75 },
  { id: 'bungkus_teh', name: 'Bungkus teh', emoji: '🍵', price: 75 },
  { id: 'bungkus_susu', name: 'Kemasan susu', emoji: '🥛', price: 100 },
  { id: 'bungkus_nasi', name: 'Bungkus nasi', emoji: '🍚', price: 100 },
  { id: 'bungkus_sambal', name: 'Sachet sambal', emoji: '🌶️', price: 50 },
  { id: 'bungkus_saos', name: 'Sachet saus', emoji: '🥫', price: 50 },
  { id: 'tisu_bekas', name: 'Tisu bekas', emoji: '🧻', price: 50 },
  { id: 'tisu_basah', name: 'Tisu basah bekas', emoji: '🧻', price: 50 },
  { id: 'puntung_rokok', name: 'Puntung rokok', emoji: '🚬', price: 50 },
  { id: 'bungkus_rokok', name: 'Bungkus rokok', emoji: '🚬', price: 100 },
  { id: 'korek_api', name: 'Korek api bekas', emoji: '🔥', price: 75 },
  { id: 'masker_bekas', name: 'Masker bekas', emoji: '😷', price: 50 },
  { id: 'sarung_tangan', name: 'Sarung tangan bekas', emoji: '🧤', price: 150 },
  { id: 'jas_hujan_plastik', name: 'Jas hujan plastik', emoji: '🧥', price: 200 },
  { id: 'kantong_plastik', name: 'Kantong plastik', emoji: '🛍️', price: 75 },
  { id: 'kresek_bekas', name: 'Kresek bekas', emoji: '🛍️', price: 75 },
  { id: 'bungkus_obat', name: 'Bungkus obat', emoji: '💊', price: 50 },
  { id: 'plester_bekas', name: 'Plester bekas', emoji: '🩹', price: 50 },
  { id: 'baterai_bekas', name: 'Baterai bekas', emoji: '🔋', price: 300 },
  { id: 'tali_bekas', name: 'Potongan tali', emoji: '🪢', price: 100 },
  { id: 'tali_sepatu', name: 'Tali sepatu bekas', emoji: '👟', price: 100 },
  { id: 'kaus_kaki_bekas', name: 'Kaus kaki bekas', emoji: '🧦', price: 150 },
  { id: 'sarung_tangan_plastik', name: 'Sarung tangan plastik', emoji: '🧤', price: 50 },
  { id: 'sendok_plastik', name: 'Sendok plastik', emoji: '🥄', price: 50 },
  { id: 'garpu_plastik', name: 'Garpu plastik', emoji: '🍴', price: 50 },
  { id: 'wadah_makanan', name: 'Wadah makanan', emoji: '🥡', price: 150 },
  { id: 'kotak_makanan', name: 'Kotak makanan', emoji: '🍱', price: 150 },
  { id: 'botol_kaca', name: 'Botol kaca', emoji: '🍾', price: 250 },
  { id: 'kaleng_makanan', name: 'Kaleng makanan', emoji: '🥫', price: 200 },
  { id: 'bungkus_abon', name: 'Bungkus abon', emoji: '🥩', price: 75 },
  { id: 'bungkus_sarden', name: 'Kemasan sarden', emoji: '🐟', price: 150 },
  { id: 'bungkus_sosis', name: 'Kemasan sosis', emoji: '🌭', price: 100 },
  { id: 'bungkus_makanan', name: 'Bungkus makanan', emoji: '🍱', price: 100 },
  { id: 'kertas_peta', name: 'Kertas peta bekas', emoji: '🗺️', price: 100 },
  { id: 'struk_belanja', name: 'Struk belanja', emoji: '🧾', price: 50 },
  { id: 'tiket_masuk', name: 'Tiket masuk bekas', emoji: '🎫', price: 50 },
  { id: 'baterai_headlamp', name: 'Baterai headlamp', emoji: '🔋', price: 300 },
  { id: 'plastik_perlengkapan', name: 'Plastik perlengkapan', emoji: '📦', price: 75 },
  { id: 'bungkus_pemanas', name: 'Bungkus pemanas makanan', emoji: '📦', price: 100 }
]

export const MOUNT_TITLES = [
  { minSummits: 0, title: '🥾 Pendaki Pemula' },
  { minSummits: 1, title: '🌱 Pendaki Awal' },
  { minSummits: 2, title: '⛰️ Pendaki Muda' },
  { minSummits: 3, title: '🥾 Penjelajah Jalur' },
  { minSummits: 4, title: '🌿 Pejalan Gunung' },
  { minSummits: 5, title: '⛰️ Pendaki Bukit' },
  { minSummits: 6, title: '🎒 Pembawa Ransel' },
  { minSummits: 7, title: '🌲 Penjelajah Alam' },
  { minSummits: 8, title: '🥾 Pengikut Jalur' },
  { minSummits: 9, title: '⛰️ Penjelajah Puncak' },
  { minSummits: 10, title: '🧭 Pemburu Puncak' },
  { minSummits: 11, title: '🌄 Penikmat Ketinggian' },
  { minSummits: 12, title: '🎒 Penjelajah Lereng' },
  { minSummits: 13, title: '🥾 Pengelana Gunung' },
  { minSummits: 14, title: '🌿 Penjajak Alam' },
  { minSummits: 15, title: '⛰️ Pendaki Aktif' },
  { minSummits: 16, title: '🧭 Pembaca Jalur' },
  { minSummits: 17, title: '🌄 Pengejar Senja' },
  { minSummits: 18, title: '🥾 Penempuh Lereng' },
  { minSummits: 19, title: '🌲 Penjelajah Rimba' },
  { minSummits: 20, title: '⛰️ Pendaki Berpengalaman' },
  { minSummits: 21, title: '🎒 Penakluk Jalur' },
  { minSummits: 22, title: '🧭 Pencari Jalur' },
  { minSummits: 23, title: '🌄 Pemburu Panorama' },
  { minSummits: 24, title: '🥾 Pendaki Tekun' },
  { minSummits: 25, title: '⛰️ Penakluk Bukit' },
  { minSummits: 26, title: '🌿 Penjelajah Lereng' },
  { minSummits: 27, title: '🎒 Pengelana Ketinggian' },
  { minSummits: 28, title: '🧭 Penuntun Jalur' },
  { minSummits: 29, title: '🌄 Pengejar Puncak' },
  { minSummits: 30, title: '🥾 Pendaki Andal' },
  { minSummits: 31, title: '⛰️ Penempuh Pegunungan' },
  { minSummits: 32, title: '🌲 Pengelana Hutan' },
  { minSummits: 33, title: '🎒 Pendaki Rajin' },
  { minSummits: 34, title: '🧭 Penjelajah Medan' },
  { minSummits: 35, title: '🌄 Pemburu Ketinggian' },
  { minSummits: 36, title: '🥾 Pendaki Terampil' },
  { minSummits: 37, title: '⛰️ Penakluk Lereng' },
  { minSummits: 38, title: '🌿 Pengelana Alam' },
  { minSummits: 39, title: '🎒 Penjelajah Tangguh' },
  { minSummits: 40, title: '🧭 Pencari Puncak' },
  { minSummits: 41, title: '🌄 Pendaki Berani' },
  { minSummits: 42, title: '🥾 Penjelajah Terampil' },
  { minSummits: 43, title: '⛰️ Penempuh Jalur' },
  { minSummits: 44, title: '🌲 Pengelana Pegunungan' },
  { minSummits: 45, title: '🎒 Pendaki Gigih' },
  { minSummits: 46, title: '🧭 Penjelajah Ketinggian' },
  { minSummits: 47, title: '🌄 Pemburu Panorama' },
  { minSummits: 48, title: '🥾 Pendaki Berpengalaman' },
  { minSummits: 49, title: '⛰️ Penakluk Medan' },
  { minSummits: 50, title: '🏔️ Pendaki Tangguh' },
  { minSummits: 51, title: '🌿 Penjajak Pegunungan' },
  { minSummits: 52, title: '🎒 Pengelana Tangguh' },
  { minSummits: 53, title: '🧭 Penemu Jalur' },
  { minSummits: 54, title: '🌄 Penjelajah Puncak' },
  { minSummits: 55, title: '🥾 Pendaki Konsisten' },
  { minSummits: 56, title: '⛰️ Penakluk Alam' },
  { minSummits: 57, title: '🌲 Pengelana Lereng' },
  { minSummits: 58, title: '🎒 Pendaki Bermental Baja' },
  { minSummits: 59, title: '🧭 Penjelajah Andal' },
  { minSummits: 60, title: '🏔️ Pendaki Veteran' },
  { minSummits: 61, title: '🌄 Penempuh Puncak' },
  { minSummits: 62, title: '🥾 Pengelana Ketinggian' },
  { minSummits: 63, title: '⛰️ Penakluk Jalur' },
  { minSummits: 64, title: '🌿 Penjelajah Pegunungan' },
  { minSummits: 65, title: '🎒 Pendaki Berpengalaman' },
  { minSummits: 66, title: '🧭 Pemburu Jalur' },
  { minSummits: 67, title: '🌄 Penikmat Puncak' },
  { minSummits: 68, title: '🥾 Pendaki Tangguh' },
  { minSummits: 69, title: '⛰️ Penakluk Ketinggian' },
  { minSummits: 70, title: '🏔️ Pengelana Gunung' },
  { minSummits: 71, title: '🌲 Penjelajah Alam Liar' },
  { minSummits: 72, title: '🎒 Pendaki Gigih' },
  { minSummits: 73, title: '🧭 Penempuh Pegunungan' },
  { minSummits: 74, title: '🌄 Pengejar Puncak' },
  { minSummits: 75, title: '🥾 Pendaki Senior' },
  { minSummits: 76, title: '⛰️ Penakluk Lereng' },
  { minSummits: 77, title: '🌿 Penjelajah Alam' },
  { minSummits: 78, title: '🎒 Pengelana Pegunungan' },
  { minSummits: 79, title: '🧭 Pendaki Andal' },
  { minSummits: 80, title: '🏔️ Pendaki Berkelas' },
  { minSummits: 81, title: '🌄 Penjelajah Puncak' },
  { minSummits: 82, title: '🥾 Penempuh Jalur Tangguh' },
  { minSummits: 83, title: '⛰️ Pemburu Ketinggian' },
  { minSummits: 84, title: '🌲 Pengelana Alam' },
  { minSummits: 85, title: '🎒 Pendaki Profesional' },
  { minSummits: 86, title: '🧭 Penjelajah Senior' },
  { minSummits: 87, title: '🌄 Penakluk Puncak' },
  { minSummits: 88, title: '🥾 Pendaki Teruji' },
  { minSummits: 89, title: '⛰️ Penjelajah Tangguh' },
  { minSummits: 90, title: '🏔️ Pendaki Veteran' },
  { minSummits: 91, title: '🌿 Penakluk Pegunungan' },
  { minSummits: 92, title: '🎒 Pengelana Puncak' },
  { minSummits: 93, title: '🧭 Penjelajah Ulung' },
  { minSummits: 94, title: '🌄 Pemburu Pegunungan' },
  { minSummits: 95, title: '🥾 Pendaki Teruji' },
  { minSummits: 96, title: '⛰️ Penakluk Ketinggian' },
  { minSummits: 97, title: '🌲 Penguasa Jalur' },
  { minSummits: 98, title: '🎒 Pengelana Ulung' },
  { minSummits: 99, title: '🧭 Penjelajah Legendaris' },
  { minSummits: 100, title: '🏔️ Penakluk Puncak' },

  { minSummits: 150, title: '🌄 Pendaki Elit' },
  { minSummits: 200, title: '⛰️ Penjelajah Pegunungan' },
  { minSummits: 250, title: '🌲 Penjaga Alam' },
  { minSummits: 300, title: '🥾 Penakluk Gunung' },
  { minSummits: 350, title: '🧭 Pengelana Puncak' },
  { minSummits: 400, title: '🏔️ Pendaki Agung' },
  { minSummits: 450, title: '🌄 Penguasa Jalur' },
  { minSummits: 500, title: '👑 Legenda Pendakian' },
  { minSummits: 550, title: '⛰️ Penakluk Pegunungan' },
  { minSummits: 600, title: '🏔️ Penguasa Ketinggian' },
  { minSummits: 650, title: '🌲 Legenda Pegunungan' },
  { minSummits: 700, title: '🥾 Pendaki Abadi' },
  { minSummits: 750, title: '🧭 Pengelana Legendaris' },
  { minSummits: 800, title: '🌄 Penakluk Cakrawala' },
  { minSummits: 850, title: '⛰️ Penguasa Puncak' },
  { minSummits: 900, title: '🏔️ Raja Pegunungan' },
  { minSummits: 950, title: '👑 Legenda Puncak' },
  { minSummits: 1000, title: '🏆 Master Pendakian' },

  { minSummits: 1500, title: '🌎 Penjelajah Dunia' },
  { minSummits: 2000, title: '🏔️ Penakluk Dunia' },
  { minSummits: 2500, title: '👑 Penguasa Pegunungan' },
  { minSummits: 3000, title: '🌄 Legenda Dunia' },
  { minSummits: 3500, title: '⛰️ Grand Pendaki' },
  { minSummits: 4000, title: '🏆 Master Pegunungan' },
  { minSummits: 4500, title: '🌎 Penjelajah Tanpa Batas' },
  { minSummits: 5000, title: '👑 Raja Puncak' },
  { minSummits: 5500, title: '🏔️ Penguasa Ketinggian' },
  { minSummits: 6000, title: '🌄 Legenda Pegunungan' },
  { minSummits: 6500, title: '🏆 Grand Master Pendakian' },
  { minSummits: 7000, title: '⛰️ Penakluk Segala Puncak' },
  { minSummits: 7500, title: '🌎 Legenda Pendaki Dunia' },
  { minSummits: 8000, title: '👑 Penguasa Puncak Dunia' },
  { minSummits: 8500, title: '🏔️ Raja Pegunungan Dunia' },
  { minSummits: 9000, title: '🌄 Abadi di Puncak' },
  { minSummits: 9500, title: '🏆 Ikon Pendakian Dunia' },
  { minSummits: 10000, title: '👑 Legenda Abadi Pegunungan' }
]

export const getMountTitle = summits => MOUNT_TITLES
  .filter(item => summits >= item.minSummits)
  .at(-1)?.title || MOUNT_TITLES[0].title

export const MOUNT_STORIES = [
  'Jalur mulai menanjak saat kabut turun. Di dekat batu penanda, kalian melihat {trash} tergeletak. Kalian mengambilnya dan menyimpannya di tas sebelum melanjutkan langkah.',
  'Angin dingin menyambut di jalur terbuka. Sebuah {trash} terselip di antara semak; kalian memungutnya agar jalur tetap bersih.',
  'Setelah melewati tanjakan berbatu, kalian menemukan {trash} di tepi jalur. Sampah itu masuk ke tas untuk dibuang pada tempatnya nanti.',
  'Suasana hutan begitu tenang, sampai terlihat {trash} dekat pos istirahat. Kalian membersihkannya bersama sebelum meneruskan pendakian.',
  'Perjalanan terasa panjang, tetapi pemandangan membuat lelah terbayar. Kalian menemukan {trash}, lalu membawanya turun agar tidak mencemari gunung.',
  'Di tengah jalur yang sepi, kalian melihat {trash} tertinggal di dekat akar pohon. Salah satu dari kalian segera memungutnya.',
  'Kalian berhenti sebentar untuk mengatur napas. Saat hendak beristirahat, terlihat {trash} di sekitar tempat tersebut. Kalian membereskannya terlebih dahulu.',
  'Jalur semakin sempit ketika kalian menemukan {trash} tersangkut di ranting. Dengan hati-hati, kalian mengambilnya tanpa merusak tanaman di sekitar.',
  'Suara langkah kaki pendaki lain terdengar dari belakang. Sebelum melanjutkan perjalanan, kalian menemukan {trash} dan membawanya bersama.',
  'Di dekat papan petunjuk jalur, ada {trash} yang ditinggalkan pendaki sebelumnya. Kalian mengambilnya dan memasukkannya ke dalam tas.',
  'Matahari mulai tertutup awan. Di pinggir jalur, kalian menemukan {trash} yang terbawa angin. Kalian memungutnya agar tidak semakin jauh terbawa.',
  'Tanjakan panjang membuat langkah melambat. Di sela istirahat, kalian melihat {trash} di tanah dan memutuskan untuk membawanya turun.',
  'Kalian melewati area yang dipenuhi pepohonan tinggi. Di bawah salah satu pohon terdapat {trash}. Kalian mengambilnya sebelum kembali berjalan.',
  'Jalur tanah berubah menjadi bebatuan. Di antara bebatuan tersebut terlihat {trash}. Kalian berhenti sejenak untuk membersihkannya.',
  'Kabut semakin tebal saat kalian mendekati pos berikutnya. Di pinggir jalur terlihat {trash} yang cukup mencolok. Kalian memungutnya dan menyimpannya.',
  'Kalian menemukan {trash} tidak jauh dari bekas tempat istirahat pendaki. Sampah tersebut langsung kalian masukkan ke tas.',
  'Suasana mulai ramai karena banyak pendaki turun. Di tengah jalur, kalian melihat {trash} tertinggal. Kalian mengambilnya sebelum melanjutkan perjalanan.',
  'Angin gunung bertiup cukup kencang. Sebuah {trash} terlihat tersangkut di semak. Kalian menariknya perlahan dan membawanya pergi.',
  'Di dekat sumber air, kalian menemukan {trash} yang tertinggal. Kalian membersihkan area tersebut agar tetap nyaman untuk pendaki lain.',
  'Kalian berhenti di sebuah batu besar untuk beristirahat. Tidak jauh dari sana terdapat {trash}. Salah satu anggota tim segera memungutnya.',
  'Jalur mulai dipenuhi akar pohon. Di sela-selanya kalian menemukan {trash}. Kalian mengambilnya dengan hati-hati agar tidak tersangkut kembali.',
  'Setelah melewati jembatan kecil, kalian melihat {trash} di ujung jalur. Kalian membawanya bersama sampai menemukan tempat pembuangan.',
  'Pemandangan mulai terbuka ketika kalian menemukan {trash} di pinggir tebing. Kalian mengambilnya agar tidak terbawa angin ke bawah.',
  'Kalian mendengar suara burung dari dalam hutan. Di dekat tempat tersebut terdapat {trash}. Kalian memungutnya sebelum melanjutkan perjalanan.',
  'Jalur terasa licin setelah hujan. Saat berjalan lebih hati-hati, kalian melihat {trash} di tanah dan mengambilnya.',
  'Di dekat tikungan jalur, sebuah {trash} terlihat di antara daun kering. Kalian membersihkannya dan kembali melanjutkan pendakian.',
  'Kalian sampai di area datar yang sering digunakan pendaki untuk beristirahat. Sayangnya, ada {trash} yang tertinggal. Kalian membawanya turun.',
  'Semakin tinggi kalian berjalan, udara terasa semakin dingin. Di tengah perjalanan kalian menemukan {trash} dan memutuskan untuk tidak membiarkannya tertinggal.',
  'Kalian melihat jejak pendaki sebelumnya di tanah. Tidak jauh dari sana terdapat {trash}. Kalian memungutnya sambil melanjutkan perjalanan.',
  'Matahari mulai muncul dari balik awan. Saat menikmati pemandangan, kalian menyadari ada {trash} di dekat kaki kalian dan segera mengambilnya.',
  'Di antara rerumputan tinggi terlihat {trash} yang hampir tertutup daun. Kalian menemukannya dan membawanya bersama.',
  'Kalian melewati jalur yang cukup ramai. Di salah satu sisi jalur terdapat {trash}. Kalian memungutnya sebelum pendaki lain melewatinya.',
  'Suara angin terdengar di antara pepohonan. Di dekat batang pohon kalian menemukan {trash} yang ditinggalkan. Sampah itu langsung masuk ke tas.',
  'Kalian beristirahat di dekat pos pendakian. Sebelum pergi, kalian melihat {trash} di sekitar tempat duduk dan membersihkannya.',
  'Tanjakan terakhir sebelum pos membuat napas terasa berat. Di tengah perjalanan kalian menemukan {trash}, lalu membawanya sampai ke atas.',
  'Jalur semakin berbatu dan membutuhkan langkah hati-hati. Di sela batu terlihat {trash}. Kalian mengambilnya tanpa mengganggu jalur.',
  'Kalian menemukan tempat dengan pemandangan indah. Sayangnya, ada {trash} di dekatnya. Kalian mengambilnya agar tempat tersebut tetap terjaga.',
  'Awan mulai bergerak cepat di atas gunung. Di bawah sebuah pohon terlihat {trash}. Kalian memungutnya sebelum kembali berjalan.',
  'Kalian melewati bekas tempat berkemah. Di sekitar lokasi masih ada {trash} yang tertinggal. Kalian membersihkannya sebelum meninggalkan tempat itu.',
  'Jalur mulai dipenuhi kabut tipis. Saat mencari pijakan, kalian melihat {trash} di samping batu dan segera mengambilnya.',
  'Kalian mendengar pendaki lain membicarakan pentingnya menjaga kebersihan gunung. Tidak lama kemudian kalian menemukan {trash} dan ikut membantu membersihkan jalur.',
  'Di dekat tanda arah pendakian terdapat {trash}. Kalian mengambilnya agar tanda tersebut tetap mudah terlihat oleh pendaki berikutnya.',
  'Perjalanan menuju puncak hampir selesai. Di jalur terakhir kalian menemukan {trash} dan membawanya sampai ke tempat pengumpulan sampah.',
  'Kalian menemukan {trash} tertinggal di dekat area yang biasa digunakan untuk berfoto. Setelah mengambilnya, kalian melanjutkan perjalanan.',
  'Hujan ringan mulai turun. Di tengah jalur terlihat {trash} yang basah terkena air. Kalian mengambilnya sebelum mencari tempat berteduh.',
  'Salah satu anggota tim melihat {trash} di balik semak. Kalian berhenti sebentar untuk mengambilnya dan memastikan tidak ada sampah lain di sekitar.',
  'Kalian melewati jalur yang cukup bersih, tetapi sebuah {trash} terlihat sendirian di tanah. Kalian tidak melewatkannya dan langsung memungutnya.',
  'Udara semakin dingin ketika kalian mendekati puncak. Di jalur terakhir terdapat {trash}. Kalian membawanya sebagai bagian dari perjalanan menuju puncak.',
  'Setelah menikmati pemandangan dari ketinggian, kalian melihat {trash} tertinggal di dekat tempat berdiri. Kalian mengambilnya sebelum meninggalkan lokasi.',
  'Pendakian hampir berakhir. Tas kalian memang sedikit lebih berat karena {trash}, tetapi jalur yang kalian lewati kini menjadi lebih bersih.'
]
