export function getPrisonTitle(stats) {
    const progress = (Number(stats?.routine) || 0) + (Number(stats?.talk) || 0)
    if (progress >= 200) return '👑 RAJA PENJARA'
    if (progress >= 100) return '🏆 LEGENDA JERUJI'
    if (progress >= 50) return '⚔️ VETERAN PENJARA'
    if (progress >= 25) return '🔥 NAPI TERLATIH'
    if (progress >= 10) return '🛡️ NAPI PEMULA'
    return '🔒 TAHANAN BARU'
}

/* =========================================================
   DIALOG VISIT 20x20
========================================================= */

export const dialogVisitNapi = [
    '“Akhirnya ada juga yang datang menjengukku...”','“Kau datang jauh-jauh cuma buat lihat aku di balik jeruji?”','“Aku baik-baik saja... cuma bosan dengan tembok ini.”','“Jangan khawatir. Aku masih kuat bertahan di sini.”','“Kunjunganmu benar-benar membuat waktuku terasa lebih cepat.”',
    '“Aku nggak menyangka masih ada yang mau datang menjenguk.”','“Di sini dingin dan sepi. Lumayan ada teman ngobrol.”','“Kalau kau punya kabar dari luar, ceritakan semuanya.”','“Aku sudah mulai hafal bentuk setiap sudut ruangan ini.”','“Terima kasih sudah datang. Setidaknya hari ini tidak terasa terlalu panjang.”',
    '“Bang tolong dong... kasih makan 😭”','“Aku dijebak bang, sumpah demi Tuhan”','“Udah 3 hari makan roti doang”','“Besok aku bebas kan bang? Tolong ya”','“Makasih udah mau nengok... sepi banget disini”',
    '“Lu juga hati2 bang, polisi lagi nyari2”','“Titip salam buat keluarga ya bang”','“Aku kapok bang, ga bakal ngulang lagi”','“Ada rokok ga bang? Bosen banget”','“Doain aku cepet bebas ya bang 🙏”',
    '“Bang, ada kabar terbaru dari luar nggak?”','“Hari ini rasanya lama banget berlalu.”','“Aku kangen suasana di luar sana.”','“Kalau bisa, bawain sesuatu buat dimakan ya.”','“Di sini tiap hari rasanya sama aja.”',
    '“Aku masih nggak percaya bisa berakhir di tempat kayak gini.”','“Ada yang nanyain aku di luar nggak?”','“Tolong jangan lupain aku selama aku di sini.”','“Aku cuma pengen cepat selesaiin masa tahanan ini.”','“Bang, kalau ketemu teman-teman, bilang aku baik-baik aja.”',
    '“Tidur di sini nggak pernah benar-benar nyenyak.”','“Aku mulai bosan lihat wajah yang itu-itu aja.”','“Kalau punya cerita lucu dari luar, ceritain dong.”','“Aku bakal lebih hati-hati setelah keluar nanti.”','“Rasanya aneh lihat dunia luar cuma dari balik jeruji.”',
    '“Bang, jangan sering-sering bikin aku iri sama kehidupan luar 😭”','“Aku masih punya harapan buat mulai hidup lagi setelah bebas.”','“Makasih udah nyempetin waktu buat datang.”','“Jangan lupa datang lagi kalau ada kesempatan.”','“Semoga kunjungan berikutnya aku sudah nggak ada di sini.”'
]

export const dialogVisitPengunjung = [
    '“Aku datang menjengukmu. Gimana keadaanmu di sini?”','“Ternyata benar-benar dikurung di sini, ya...”','“Aku cuma mau memastikan kamu masih baik-baik saja.”','“Sabar ya. Semoga masa tahanannya cepat selesai.”','“Aku bawa kabar dari luar. Kota masih ramai seperti biasa.”',
    '“Jangan terlalu dipikirkan. Anggap saja ini liburan yang salah tempat.”','“Aku penasaran, bagaimana rasanya menghabiskan waktu di sini?”','“Kalau butuh sesuatu, bilang saja selama masih bisa dibantu.”','“Aku sempat khawatir setelah dengar kamu masuk penjara.”','“Aku pamit dulu. Semoga kita ketemu lagi di luar jeruji.”',
    '“Sabar ya, ini ada uang buat jajan”','“Gimana ceritanya bisa masuk sini?”','“Tenang, lawyer udah gue urus”','“Jangan ngulangin lagi ya, malu”','“Mau nitip apa? Gue beliin”',
    '“Keluarga nungguin lu di luar”','“Udah tobat belum di dalem?”','“Ini selnya dingin banget sih”','“Kuat2 ya, bentar lagi juga keluar”','“Hati2 sama napi lain, jangan berantem”',
    '“Gue bawain makanan, siapa tahu lu lapar.”','“Ada yang mau gue sampaikan dari keluarga.”','“Lu jangan kepikiran yang aneh-aneh dulu.”','“Di luar semuanya masih aman, jadi lu tenang aja.”','“Gue usahain sering-sering nengok lu.”',
    '“Teman-teman lu pada nanyain kabar.”','“Kalau ada yang perlu dibantu, bilang aja.”','“Gue nggak nyangka akhirnya harus nengok lu di penjara.”','“Yang penting sekarang lu jaga diri baik-baik.”','“Nanti kalau udah keluar, jangan bikin masalah lagi.”',
    '“Gue bawain baju sekalian, siapa tahu yang lama udah nggak nyaman.”','“Lu masih kuat kan? Jangan sampai drop.”','“Ada kabar baik, semuanya masih nunggu lu pulang.”','“Jangan malu buat minta bantuan kalau memang perlu.”','“Gue lihat lu masih sehat, syukurlah.”',
    '“Kalau bosen, ngobrol aja sama orang yang ada di sini.”','“Gue cuma bisa bantu sebisanya dari luar.”','“Sabar sedikit lagi, semua ini pasti ada akhirnya.”','“Titip pesan apa buat keluarga?”','“Semoga kunjungan berikutnya kita ngobrolnya bukan di balik jeruji lagi.”'
]

/* =========================================================
   STORY KABUR 20 VARIASI - PELUANG 1%
========================================================= */

export const storyKabur = [
    { sukses: `🪟 Kamu congkel jeruji pakai sendok semalaman. Pas sipir lengah, langsung loncat keluar!`, gagal: `🪟 Sendoknya patah ditengah jalan. Ketahuan sipir dan dihajar.` },
    { sukses: `🚽 Kamu kabur lewat saluran pembuangan. Becek, bau, tapi bebas!`, gagal: `🚽 Nyangkut di pipa. Malah disemprot air kotoran.` },
    { sukses: `🎭 Kamu tukar baju sama pengunjung. Jalan keluar santai sambil lambaikan tangan.`, gagal: `🎭 Sipir ngeh ada 2 orang kembaran. Langsung diborgol lagi.` },
    { sukses: `🍰 Kamu sembunyi di dalam kue ultah kiriman. Truk sampah buang kamu ke luar.`, gagal: `🍰 Kuenya kemakan duluan sama sipir rakus. Kamu ketahuan.` },
    { sukses: `💣 Kamu buat ledakan kecil dari bedak + korek. Pas rame, kamu kabur!`, gagal: `💣 Koreknya basah. Malah kamu yg kena ledakan.` },
    { sukses: `👨‍⚕️ Pura2 sakit jantung. Pas di RS penjara kamu kabur lewat jendela.`, gagal: `👨‍⚕️ Dokternya curiga. Kamu malah diikat di ranjang.` },
    { sukses: `📦 Kamu masukin diri ke kardus pengiriman makanan. Lolos!`, gagal: `📦 Kardusnya ketiban 10 kardus lain. Pingsan 3 jam.` },
    { sukses: `🕳️ Gali terowongan 2 minggu pakai sendok. Akhirnya tembus ke selokan!`, gagal: `🕳️ Nemu pipa air. 1 penjara banjir, kamu kena hukuman.` },
    { sukses: `🚁 Tiba2 ada heli nyelametin. Tali diturunin, kamu naik!`, gagal: `🚁 Helinya salah alamat. Malah nembak ke bawah.` },
    { sukses: `🔑 Duplikat kunci dari sabun. Pintu kebuka pelan2.`, gagal: `🔑 Sabunnya meleleh. Kunci patah di dalem.` },
    { sukses: `🧹 Nyamar jadi petugas kebersihan. Dorong gerobak keluar aja.`, gagal: `🧹 Ditanya ID. Pas dicek, fotonya beda.` },
    { sukses: `⚡ Matiin sekring. Pas gelap kamu panjat tembok.`, gagal: `⚡ Genset nyala 3 detik kemudian. Ketahuan.` },
    { sukses: `🐀 Ikutin tikus yg sering keluar masuk. Ternyata ada lubang.`, gagal: `🐀 Tikusnya balik lagi ke sel. Kamu kejebak.` },
    { sukses: `🚛 Sembunyi di kolong truk sampah. Dibuang ke TPA.`, gagal: `🚛 Kepergok di TPA. Ditangkap ulang.` },
    { sukses: `🎂 Suap sipir pake kue + uang. Dia pura2 tidur.`, gagal: `🎂 Sipirnya lapor. Kue + uang disita.` },
    { sukses: `📞 Hack telepon penjara. Buka pintu elektronik dari dalem.`, gagal: `📞 Malah nyambung ke kantor polisi.` },
    { sukses: `🧨 Ledakin tembok belakang pas jam olahraga rame2.`, gagal: `🧨 Sumbunya basah. Ga nyala2.` },
    { sukses: `👔 Tukar identitas sama napi yg mau bebas besok.`, gagal: `👔 Sidik jarinya ga cocok. Ketahuan.` },
    { sukses: `🌧️ Pas hujan badai + mati lampu. Panjat tembok ga ada yg liat.`, gagal: `🌧️ Licin. Jatuh. Kaki patah.` },
    { sukses: `🤡 Tipu sipir baru yg masih magang. Bilang disuruh atasannya.`, gagal: `🤡 Ternyata dia intel. Langsung diborgol.` },
    { sukses: `🧺 Sembunyi di antara tumpukan laundry. Truk cucian bawa kamu keluar.`, gagal: `🧺 Petugas laundry nemu kamu sebelum truk berangkat.` },
    { sukses: `🎨 Nyamar jadi lukisan di dinding. Pas penjaga lewat, kamu langsung lari.`, gagal: `🎨 Sipir malah sadar lukisannya punya kaki. Ketahuan.` },
    { sukses: `🛒 Sembunyi di gerobak makanan. Keluar penjara sambil pura2 jadi katering.`, gagal: `🛒 Penjaga minta cek gerobak. Kamu langsung ketahuan.` },
    { sukses: `📚 Sembunyi di balik tumpukan buku perpustakaan. Buku dikirim keluar dan kamu ikut.`, gagal: `📚 Buku yang kamu sembunyikan jatuh. Sipir langsung curiga.` },
    { sukses: `🧑‍🍳 Nyamar jadi koki. Bawa nampan makanan sambil jalan santai ke pintu luar.`, gagal: `🧑‍🍳 Sipir minta makanan favoritnya. Kamu ga bisa masak.` },
    { sukses: `🎪 Ada acara hiburan di penjara. Kamu nyamar jadi kru panggung dan ikut keluar.`, gagal: `🎪 Kru asli datang dan langsung sadar kamu bukan anggota mereka.` },
    { sukses: `🪣 Masuk ke dalam tong besar dan ikut dibawa petugas kebersihan.`, gagal: `🪣 Tongnya dibuka sebelum keluar. Sipir langsung menemukanmu.` },
    { sukses: `🚪 Kamu pura2 jadi petugas inspeksi. Semua orang sibuk, kamu jalan keluar tanpa dicurigai.`, gagal: `🚪 Penjaga minta surat tugas. Kamu cuma bisa senyum.` },
    { sukses: `🧤 Nyamar jadi teknisi dan bawa kotak peralatan menuju gerbang.`, gagal: `🧤 Teknisi asli muncul di belakangmu. Penyamarannya tamat.` },
    { sukses: `🛏️ Sembunyi di bawah kasur lipat yang dibawa keluar saat pergantian barang.`, gagal: `🛏️ Kasurnya diperiksa sebelum keluar. Kamu langsung ditemukan.` },
    { sukses: `📦 Pura2 jadi paket penting dan ikut kendaraan pengiriman keluar penjara.`, gagal: `📦 Petugas memeriksa paket dan menemukan kamu di dalam.` },
    { sukses: `🧢 Pinjam topi sipir dan jalan tegap melewati lorong. Aneh tapi berhasil!`, gagal: `🧢 Topinya kebesaran dan jatuh. Wajahmu langsung kelihatan.` },
    { sukses: `🧼 Sembunyi di ruang mandi sampai pergantian shift. Saat sepi, kamu keluar lewat pintu servis.`, gagal: `🧼 Sipir melakukan pemeriksaan mendadak dan menemukanmu.` },
    { sukses: `📢 Kamu bikin pengumuman palsu lewat pengeras suara. Semua sipir pergi ke blok lain.`, gagal: `📢 Suaramu dikenali. Sipir langsung menuju selmu.` },
    { sukses: `🕰️ Kamu hafal jadwal patroli selama berhari2. Celah kecil akhirnya muncul dan kamu kabur.`, gagal: `🕰️ Jadwal patroli berubah mendadak. Kamu malah ketemu sipir.` },
    { sukses: `🪑 Kamu bongkar kursi tua dan menemukan ruang kosong di dalamnya.`, gagal: `🪑 Kursinya ambruk saat kamu masuk. Suaranya bikin sipir datang.` },
    { sukses: `🐕 Kamu mengikuti petugas membawa anjing penjaga sampai ke area luar, lalu menyelinap pergi.`, gagal: `🐕 Anjing penjaga malah mencium keberadaanmu dan menggonggong keras.` },
    { sukses: `🚿 Kamu menyusuri saluran air kecil sampai menemukan pintu keluar di belakang penjara.`, gagal: `🚿 Salurannya buntu. Kamu balik dan sudah ditunggu sipir.` },
    { sukses: `🧑‍🔧 Nyamar jadi teknisi listrik dan pura2 memperbaiki lampu dekat gerbang.`, gagal: `🧑‍🔧 Petugas listrik asli datang. Identitasmu langsung terbongkar.` },
    { sukses: `🎤 Ikut rombongan acara penjara sebagai kru suara. Begitu keluar gerbang, kamu langsung kabur.`, gagal: `🎤 Panitia menghitung anggota dan sadar ada orang asing di rombongan.` },
    { sukses: `🛍️ Masuk ke kantong besar perlengkapan yang akan dikirim keluar. Kali ini lolos mulus.`, gagal: `🛍️ Kantongnya diperiksa satu per satu. Kamu ketahuan sebelum kendaraan jalan.` },
    { sukses: `🌳 Kamu menyelinap lewat area taman belakang yang jarang dijaga dan memanjat pagar.`, gagal: `🌳 Sensor pagar berbunyi saat kamu baru setengah jalan.` },
    { sukses: `🔔 Kamu bikin suara alarm palsu di blok sebelah. Semua sipir berlari ke sana dan kamu kabur.`, gagal: `🔔 Alarm palsumu gagal dan malah membuat sipir mengecek selmu.` },
    { sukses: `🧑‍🎨 Nyamar sebagai pekerja renovasi. Helm dipakai, muka ditunduk, langsung keluar.`, gagal: `🧑‍🎨 Mandor meminta nama proyek. Kamu salah jawab dan langsung dicurigai.` },
    { sukses: `🚲 Kamu menyelinap ke kendaraan petugas yang diparkir dekat gerbang dan keluar bersama rombongan.`, gagal: `🚲 Kendaraannya diperiksa sebelum berangkat. Kamu ketahuan di dalam.` },
    { sukses: `🪴 Sembunyi di balik tanaman besar yang dipindahkan ke luar kompleks.`, gagal: `🪴 Tanamannya jatuh saat dibawa. Persembunyianmu langsung terbongkar.` },
    { sukses: `🧯 Kamu membuat kepanikan kecil dengan alarm kebakaran lalu menyelinap lewat pintu darurat.`, gagal: `🧯 Alarm kebakaran langsung memicu penguncian otomatis. Kamu malah terjebak.` },
    { sukses: `🧳 Masuk ke dalam koper besar milik pengunjung dan berhasil keluar tanpa diperiksa.`, gagal: `🧳 Koper dibuka petugas keamanan. Kamu langsung ketahuan.` },
    { sukses: `🕵️ Kamu pura2 jadi penyidik yang datang memeriksa tahanan. Ajaibnya semua orang percaya.`, gagal: `🕵️ Salah satu sipir benar2 kenal semua penyidik. Identitasmu terbongkar.` },
    { sukses: `🛠️ Ikut rombongan pekerja renovasi sampai gerbang, lalu kabur saat semua sibuk membawa peralatan.`, gagal: `🛠️ Mandor menghitung pekerja dan sadar ada satu orang tambahan.` },
    { sukses: `🌙 Kamu menunggu tengah malam, merangkak melewati sisi gelap halaman, lalu berhasil mencapai luar.`, gagal: `🌙 Lampu sorot tiba2 menyala tepat saat kamu menyeberang halaman.` },
    { sukses: `🎒 Kamu sembunyi di tas perlengkapan olahraga dan ikut dibawa keluar setelah pertandingan.`, gagal: `🎒 Tasmu terasa terlalu berat. Petugas membukanya dan langsung menemukanmu.` },
    { sukses: `🧱 Kamu menemukan bagian tembok yang rusak dan memanjatnya saat semua penjaga sedang berganti shift.`, gagal: `🧱 Temboknya runtuh saat kamu memanjat. Suaranya membangunkan satu blok.` }
]

export const storyBreakout = {
    sukses: [
        `🧱 Kalian merobohkan dinding tua bersama-sama dan menyelinap keluar sebelum sipir datang.`,
        `🚨 Alarm berbunyi saat pergantian jaga. Kalian memanfaatkan kekacauan untuk lolos bersama.`,
        `🪢 Dengan tali dari kain seprai, kalian turun melewati tembok dan berhasil mencapai luar.`,
        `🚚 Kalian bersembunyi di kendaraan pengangkut logistik dan lolos dari gerbang penjara.`,
        `🌧️ Hujan deras menutupi suara langkah kalian. Satu per satu berhasil melewati pagar penjara.`,
        `🗝️ Salah satu dari kalian berhasil mendapatkan kunci cadangan. Pintu blok terbuka dan kalian melarikan diri.`,
        `🔧 Kalian menggunakan peralatan seadanya untuk membuka jalur servis dan keluar dari area penjara.`,
        `🌙 Kalian menunggu sampai malam tiba sebelum bergerak diam-diam melewati area penjagaan.`,
        `📦 Kalian menyusup ke dalam peti logistik dan berhasil keluar bersama pengiriman tanpa terdeteksi.`,
        `🕳️ Kalian menemukan celah sempit di bawah pagar dan berhasil melewatinya satu per satu.`,
        `🚪 Pintu lorong terbuka saat pergantian shift. Kalian bergerak cepat sebelum penjaga kembali.`,
        `🧱 Salah satu bagian tembok ternyata sudah rapuh. Kalian membukanya bersama-sama dan berhasil kabur.`,
        `🔦 Kalian mematikan sumber penerangan di blok dan menggunakan kegelapan untuk melewati penjagaan.`,
        `📻 Kalian memanfaatkan gangguan komunikasi antarpenjaga untuk menyelinap menuju pintu keluar.`,
        `🪜 Kalian menemukan tangga tua di ruang penyimpanan dan menggunakannya untuk melewati tembok pembatas.`,
        `🚿 Kalian melewati jalur saluran air yang jarang digunakan dan berhasil keluar dari area utama penjara.`,
        `🧥 Kalian menyamar menggunakan pakaian yang ditemukan di ruang penyimpanan dan berhasil melewati satu pos penjagaan.`,
        `🚨 Kekacauan terjadi di blok sebelah. Kalian memanfaatkan situasi untuk bergerak menuju jalur pelarian.`,
        `🌫️ Kabut tebal menutupi halaman penjara. Kalian berjalan merunduk hingga berhasil melewati pagar luar.`,
        `🪢 Tali buatan kalian cukup kuat untuk mencapai sisi luar tembok. Semua anggota berhasil turun dengan selamat.`,
        `🔐 Kalian berhasil membuka pintu besi yang selama ini menjadi penghalang utama dan menemukan jalan keluar.`,
        `🚛 Kendaraan pengangkut berhenti di area belakang. Kalian menyelinap masuk dan berhasil keluar dari kompleks.`,
        `🧭 Salah satu anggota menemukan rute tersembunyi menuju bagian belakang penjara. Kalian mengikuti jalur itu hingga lolos.`,
        `💡 Listrik padam selama beberapa menit. Kalian langsung bergerak dan berhasil melewati beberapa titik penjagaan.`,
        `🏃 Kalian berpencar untuk mengalihkan perhatian penjaga, lalu berkumpul kembali setelah berhasil keluar.`,
        `🪟 Kalian membuka jendela kecil di ruang lama dan menggunakannya sebagai jalan keluar dari blok.`,
        `🌧️ Hujan deras membuat penjaga berlindung di pos. Kalian menggunakan kesempatan itu untuk menembus pagar.`,
        `📦 Kalian bersembunyi di antara tumpukan perlengkapan dan keluar bersama rombongan logistik.`,
        `🧱 Setelah bekerja diam-diam selama berhari-hari, kalian akhirnya berhasil membuat celah pada dinding.`,
        `🗺️ Peta lama yang ditemukan salah satu anggota menunjukkan jalur servis yang tidak lagi digunakan.`,
        `🔑 Kunci yang ditemukan secara kebetulan ternyata cocok dengan pintu akses luar. Kalian langsung memanfaatkannya.`,
        `🚧 Penjagaan di gerbang berkurang saat pergantian petugas. Kalian bergerak cepat melewati celah tersebut.`,
        `🌙 Kalian menunggu waktu yang tepat, lalu bergerak dalam kegelapan hingga seluruh tim berhasil keluar.`,
        `🔧 Kalian memperbaiki alat sederhana yang dibutuhkan untuk membuka pintu servis dan berhasil melarikan diri.`,
        `📣 Keributan di blok lain mengalihkan perhatian penjaga. Kalian menggunakan kesempatan itu untuk kabur.`,
        `🕳️ Sebuah lubang tersembunyi di balik tumpukan barang membawa kalian menuju lorong luar.`,
        `🚪 Kalian berhasil mengunci pintu di belakang sehingga penjaga terlambat mengejar.`,
        `🪜 Tangga darurat yang jarang diperiksa menjadi jalan kalian menuju bagian luar kompleks.`,
        `🚚 Kalian menunggu kendaraan logistik terbuka dan menyelinap keluar saat penjaga sedang memeriksa muatan.`,
        `🔦 Kalian bergerak mengikuti bayangan tembok dan berhasil melewati titik patroli tanpa terlihat.`,
        `📻 Gangguan radio membuat koordinasi penjaga kacau. Kalian memanfaatkan kesempatan itu untuk meloloskan diri.`,
        `🌫️ Asap dan debu memenuhi salah satu area penjara. Kalian menggunakannya sebagai perlindungan untuk kabur.`,
        `🧤 Kalian menemukan perlengkapan kerja dan menggunakannya untuk menyamarkan diri saat melewati area terbatas.`,
        `🔓 Pintu yang seharusnya terkunci ternyata tidak rapat. Kalian membukanya perlahan dan menemukan jalan keluar.`,
        `🏚️ Bangunan tua di sisi kompleks memiliki akses langsung ke luar. Kalian berhasil menemukannya tepat waktu.`,
        `🚨 Sistem keamanan mengalami gangguan singkat. Kalian bergerak cepat sebelum semuanya kembali normal.`,
        `🪢 Kalian menggabungkan beberapa potong kain menjadi tali panjang dan berhasil melewati tembok luar.`,
        `🧭 Setelah berjam-jam mencari jalan, kalian menemukan pintu servis yang mengarah langsung ke luar.`,
        `🏃 Semua anggota berlari menuju titik persembunyian setelah berhasil melewati pagar. Tidak ada yang tertinggal.`,
        `🌅 Kalian berhasil bertahan hingga pergantian shift pagi dan menyelinap keluar sebelum penjagaan kembali diperketat.`
    ],
    gagal: [
        `🔦 Sipir memergoki kalian di lorong. Rencana buyar dan semuanya tertangkap kembali.`,
        `🚪 Pintu darurat terkunci rapat. Alarm menyala sebelum kalian sempat menemukan jalan lain.`,
        `🪢 Tali kain yang kalian buat putus di tengah jalan. Sipir segera mengepung kalian.`,
        `🚧 Gerbang luar mendadak ditutup saat kalian hampir mencapainya. Kalian tertangkap di halaman.`,
        `📣 Salah satu penjaga mendengar keributan dan memanggil bantuan. Seluruh tim gagal kabur.`,
        `🔐 Kunci yang kalian gunakan ternyata salah. Pintu tidak terbuka dan penjaga datang sebelum kalian mencoba lagi.`,
        `🚨 Alarm keamanan berbunyi tepat saat kalian melewati lorong terlarang. Penjaga langsung mengepung area.`,
        `🔦 Cahaya senter menyapu tempat persembunyian kalian. Tidak ada waktu untuk melarikan diri.`,
        `🧱 Dinding yang kalian coba tembus ternyata jauh lebih kuat dari dugaan. Waktu habis sebelum jalur terbuka.`,
        `🚔 Kendaraan logistik diperiksa sebelum keluar. Persembunyian kalian terbongkar dan semuanya ditangkap.`,
        `📻 Komunikasi penjaga berjalan lancar malam itu. Gerakan kalian langsung diketahui dari satu pos ke pos lainnya.`,
        `🪜 Tangga yang kalian gunakan patah sebelum semua anggota berhasil melewatinya. Penjaga keburu datang.`,
        `🌧️ Hujan berhenti terlalu cepat. Suara langkah kalian terdengar jelas dan membuat penjaga curiga.`,
        `🚪 Pintu yang kalian buka mengarah ke pos penjagaan. Kalian langsung berhadapan dengan beberapa sipir.`,
        `🕳️ Celah yang ditemukan ternyata terlalu sempit. Kalian terjebak dan penjaga datang sebelum bisa keluar.`,
        `🔦 Salah satu anggota menyalakan cahaya secara tidak sengaja. Posisi kalian langsung terungkap.`,
        `🚨 Listrik kembali menyala saat kalian sedang bergerak. Seluruh area mendadak terang dan kalian tertangkap.`,
        `📦 Peti tempat kalian bersembunyi dibuka sebelum kendaraan meninggalkan penjara. Rencana gagal total.`,
        `🧭 Kalian salah mengikuti jalur dan justru kembali ke blok utama. Penjaga sudah menunggu di sana.`,
        `🔑 Kunci berhasil diputar, tetapi pintunya mengeluarkan suara keras. Sipir datang sebelum kalian sempat keluar.`,
        `🚧 Gerbang kedua ternyata masih terkunci. Kalian terjebak di antara dua lapis penjagaan.`,
        `📣 Suara langkah salah satu anggota terlalu keras. Penjaga langsung memeriksa lorong dan menemukan kalian.`,
        `🪢 Tali buatan kalian tidak cukup panjang untuk mencapai sisi luar. Kalian terpaksa kembali dan tertangkap.`,
        `🌙 Malam yang seharusnya sepi ternyata menjadi waktu patroli tambahan. Kalian langsung ketahuan.`,
        `🚓 Dua regu penjaga muncul dari arah berlawanan. Jalur pelarian kalian tertutup sepenuhnya.`,
        `🔧 Alat yang kalian gunakan rusak sebelum pintu terbuka. Waktu terus berjalan dan penjaga mendekat.`,
        `🧱 Bagian tembok runtuh terlalu keras. Suaranya terdengar hingga pos penjagaan dan membuat kalian tertangkap.`,
        `📹 Kamera keamanan menangkap gerakan kalian. Petugas segera menuju lokasi sebelum kalian keluar.`,
        `🚨 Alarm berbunyi beberapa detik setelah kalian membuka pintu. Seluruh kompleks masuk dalam keadaan siaga.`,
        `🧥 Penyamaran kalian tidak meyakinkan. Seorang penjaga menghentikan kalian dan meminta identitas.`,
        `🔦 Penjaga melakukan pemeriksaan mendadak di area yang kalian jadikan jalur pelarian.`,
        `🚪 Pintu keluar tertutup otomatis sebelum anggota terakhir berhasil melewatinya. Tim akhirnya terkepung.`,
        `📻 Salah satu radio penjaga menangkap percakapan kalian. Lokasi persembunyian langsung diketahui.`,
        `🏃 Kalian mencoba berlari melewati halaman, tetapi lampu sorot langsung mengarah kepada kalian.`,
        `🕳️ Jalur bawah tanah ternyata buntu. Saat kalian kembali, penjaga sudah memenuhi pintu masuk.`,
        `🚚 Kendaraan yang hendak kalian gunakan pergi lebih cepat dari perkiraan. Kalian tertinggal dan tertangkap.`,
        `🌫️ Kabut tidak cukup tebal untuk menutupi gerakan kalian. Patroli melihat bayangan kalian di kejauhan.`,
        `🔐 Pintu terakhir membutuhkan akses khusus yang tidak kalian miliki. Waktu habis sebelum bantuan datang.`,
        `📣 Keributan kecil berubah menjadi alarm besar. Seluruh penjaga langsung bergerak menuju posisi kalian.`,
        `🪟 Jendela yang kalian jadikan jalan keluar ternyata dipasangi jeruji tambahan. Rencana terhenti di tengah jalan.`,
        `🚧 Jalur servis mendadak ditutup untuk pemeriksaan rutin. Kalian terjebak sebelum mencapai pintu luar.`,
        `🔎 Penjaga menemukan jejak kalian di lorong. Mereka mengikuti jejak tersebut sampai menemukan seluruh tim.`,
        `💡 Lampu darurat menyala tepat ketika kalian melewati halaman. Semua gerakan kalian terlihat jelas.`,
        `🚔 Mobil patroli sudah menunggu di luar pagar. Bahkan setelah keluar dari blok, kalian tetap tidak bisa lolos.`,
        `🧱 Celah pada dinding runtuh sebelum semua anggota melewatinya. Sebagian tim terjebak dan akhirnya semuanya tertangkap.`,
        `🗺️ Peta yang kalian gunakan ternyata sudah tidak sesuai dengan kondisi penjara. Kalian tersesat dan masuk ke area penjagaan.`,
        `🔦 Salah satu sipir sedang melakukan patroli tepat di jalur yang kalian pilih. Tidak ada kesempatan untuk bersembunyi.`,
        `🚨 Sistem keamanan mendeteksi pintu yang terbuka dan mengunci seluruh akses keluar. Rencana kalian gagal.`,
        `🏃 Kalian hampir mencapai titik aman, tetapi salah satu anggota tertinggal. Penjaga berhasil mengejar dan menangkap semuanya.`
    ]
}

/* =========================================================
   STORY ROUTINE 50 VARIASI
========================================================= */

export const storyRoutine = [
    `📖 *Hari ini:* Bangun jam 5, sholat di pojokan sel. Makan roti keras + air putih. Siangnya nyapu 1 jam. Malam baca koran bekas sampe ketiduran.`,
    `📖 *Hari ini:* Ikut kerja bakti bersihin halaman penjara. Keringetan banget. Dapet bonus es teh. Tidur di kasur tipis sambil mikir keluarga.`,
    `📖 *Hari ini:* Bertengkar sama napi sebelah gara-gara rebutan sabun. Didamaikan sipir. Sorenya olahraga lari 3x keliling lapangan.`,
    `📖 *Hari ini:* Diajarin tukang kayu bikin kursi. Jari ketusuk paku. Tapi lumayan dapet skill baru.`,
    `📖 *Hari ini:* Kirim surat ke rumah. Nunggu 2 jam buat dapet giliran nelpon. Cuma 5 menit, tapi rasanya berharga banget.`,
    `📖 *Hari ini:* Ikut pengajian. Ustadnya ceramah tentang tobat. Banyak yang diam merenung, termasuk gue.`,
    `📖 *Hari ini:* Masak nasi buat 50 orang. Ketumpahan. Akhirnya disuruh cuci piring seharian.`,
    `📖 *Hari ini:* Sakit perut. Ke klinik, dikasih obat. Setelah itu cuma tiduran seharian di sel.`,
    `📖 *Hari ini:* Main catur sama napi seumur. Kalah 5x berturut-turut. Harga diri anjlok.`,
    `📖 *Hari ini:* Dapet kiriman dari rumah: baju, mie, dan beberapa makanan. Sebagian gue bagi ke teman satu sel.`,
    `📖 *Hari ini:* Disuruh cat tembok. Catnya kena muka. Teman-teman malah ketawa karena katanya mirip badut.`,
    `📖 *Hari ini:* Hujan deras, air masuk ke sel. Tidur sambil mindahin barang-barang biar nggak basah.`,
    `📖 *Hari ini:* Nonton TV bareng. Cuma ada sinetron. Ujung-ujungnya malah ribut rebutan remote.`,
    `📖 *Hari ini:* Dipanggil kepala penjara. Dikasih nasihat hampir satu jam. Panjang banget, tapi ada beberapa yang masuk akal.`,
    `📖 *Hari ini:* Ikut lomba kebersihan antar sel. Cuma juara 3, tapi dapet sabun tambahan.`,
    `📖 *Hari ini:* Mimpi kabur semalam. Begitu bangun, masih lihat jeruji. Cuma bisa narik napas panjang.`,
    `📖 *Hari ini:* Belajar baca tulis sama relawan. Dulu susah nulis nama sendiri, sekarang sudah mulai lancar.`,
    `📖 *Hari ini:* Berantem kecil di dapur. Piring pecah dan semua langsung kena omel sipir.`,
    `📖 *Hari ini:* Duduk di pojokan sambil ngitung hari. Rasanya angka di kalender jalan lebih lambat dari biasanya.`,
    `📖 *Hari ini:* Sepi banget. Akhirnya ngobrol sama tembok. Temboknya tentu aja diem.`,
    `📖 *Hari ini:* Dapet giliran bersihin kamar mandi. Bau banget, tapi setidaknya waktu jadi terasa lebih cepat.`,
    `📖 *Hari ini:* Pagi-pagi ikut senam. Niatnya cuma gerak sedikit, malah pegal seharian.`,
    `📖 *Hari ini:* Ada napi baru masuk. Semua orang penasaran sama ceritanya, tapi gue memilih diam.`,
    `📖 *Hari ini:* Dapet jatah buah. Pisangnya kecil banget, tapi tetap habis dalam hitungan detik.`,
    `📖 *Hari ini:* Bantu napi sebelah benerin sandal. Ternyata cuma putus talinya. Lumayan bisa merasa berguna.`,
    `📖 *Hari ini:* Seharian panas banget. Kipas cuma muter pelan, jadi lebih banyak duduk di dekat jendela.`,
    `📖 *Hari ini:* Denger suara kendaraan dari luar. Sebentar aja, tapi langsung bikin kangen suasana jalanan.`,
    `📖 *Hari ini:* Dapet kesempatan baca buku lama dari perpustakaan. Sampai lupa kalau sedang ada di penjara.`,
    `📖 *Hari ini:* Bantu masak makan siang. Kali ini nggak tumpah dan nggak gosong. Kemajuan besar.`,
    `📖 *Hari ini:* Ada yang ulang tahun di blok sebelah. Cuma dirayain sederhana, tapi semua ikut senang.`,
    `📖 *Hari ini:* Bangun kesiangan dan hampir kelewatan jadwal makan. Untung teman satu sel bangunin.`,
    `📖 *Hari ini:* Dikasih tugas lipat pakaian. Kelihatannya gampang, ternyata satu tumpuk penuh.`,
    `📖 *Hari ini:* Main kartu sampai sore. Nggak ada taruhan, cuma buat bunuh waktu.`,
    `📖 *Hari ini:* Denger kabar kalau salah satu teman sebentar lagi bebas. Ikut senang sekaligus iri sedikit.`,
    `📖 *Hari ini:* Dapat surat balasan dari rumah. Cuma beberapa kalimat, tapi gue baca berkali-kali.`,
    `📖 *Hari ini:* Ada pemeriksaan mendadak. Semua langsung buru-buru merapikan barang masing-masing.`,
    `📖 *Hari ini:* Belajar bikin kerajinan tangan dari kertas bekas. Hasilnya jelek, tapi lumayan buat mengisi waktu.`,
    `📖 *Hari ini:* Duduk di halaman saat matahari sore. Jarang banget bisa menikmati udara luar walau cuma sebentar.`,
    `📖 *Hari ini:* Salah ambil sandal punya orang. Baru sadar setelah dipakai jalan beberapa meter.`,
    `📖 *Hari ini:* Napi sebelah cerita tentang keluarganya sampai malam. Gue cuma dengerin dan sesekali ikut menanggapi.`,
    `📖 *Hari ini:* Bangun karena suara hujan. Untuk beberapa menit suasana terasa tenang banget.`,
    `📖 *Hari ini:* Dapet jatah tambahan nasi. Hari ini rasanya sedikit lebih beruntung.`,
    `📖 *Hari ini:* Bantu bersihin halaman setelah hujan. Lumpur di mana-mana, sepatu jadi berat.`,
    `📖 *Hari ini:* Ada pertandingan olahraga kecil. Gue ikut main dan pulang dengan badan pegal semua.`,
    `📖 *Hari ini:* Seharian kepikiran rumah. Nggak banyak aktivitas, cuma duduk dan menunggu waktu berjalan.`,
    `📖 *Hari ini:* Ketemu napi lama yang sudah hafal semua rutinitas di sini. Banyak cerita yang dia kasih.`,
    `📖 *Hari ini:* Dapat kesempatan telepon keluarga. Waktunya singkat, tapi cukup buat bikin hati sedikit tenang.`,
    `📖 *Hari ini:* Bantu merapikan rak buku. Nemunya beberapa buku lama yang ternyata masih menarik dibaca.`,
    `📖 *Hari ini:* Malam ini lebih tenang dari biasanya. Setelah semua kegiatan selesai, gue cuma rebahan sambil menatap langit-langit.`
]

/* =========================================================
   STORY TALK 50 VARIASI
========================================================= */

export const storyTalk = [
    `💬 Kamu: 'Gimana cara cepet keluar?'\n👤 Napi A: 'Tunggu aja bang, waktunya pasti lewat. Sabar.'`,
    `💬 Kamu: 'Lu kasus apa?'\n👤 Napi B: 'Copet bang. Gue nyesel sekarang.'\n> Kamu: 'Semoga setelah keluar nggak diulang lagi.'`,
    `💬 Kamu: 'Bosen ga?'\n👤 Napi C: 'Bosen lah. Makanya gue bikin permainan sendiri dari barang bekas.'`,
    `💬 Kamu: 'Sipir galak ga?'\n👤 Napi D: 'Ada yang tegas, ada yang santai. Tergantung situasi.'`,
    `💬 Kamu: 'Pernah kepikiran kabur?'\n👤 Napi E: 'Pernah kepikiran. Tapi konsekuensinya lebih panjang.'`,
    `💬 Kamu: 'Makanan enak ga?'\n👤 Napi F: 'Lumayan kalau lagi lapar. Kalau dibanding masakan rumah, ya beda.'`,
    `💬 Kamu: 'Kangen rumah?'\n👤 Napi G: 'Banget. Apalagi kalau ingat keluarga.'`,
    `💬 Kamu: 'Ada wifi ga?'\n👤 Napi H: 'Nggak ada. Yang ada cuma koneksi sama sesama napi.'`,
    `💬 Kamu: 'Lu nyesel?'\n👤 Napi I: 'Nyesel. Kalau bisa muter waktu, gue pasti mikir dua kali.'`,
    `💬 Kamu: 'Gimana biar ga gila?'\n👤 Napi J: 'Ngobrol, olahraga, baca. Jangan diem terus.'`,
    `💬 Kamu: 'Ada yang serem di sini?'\n👤 Napi K: 'Yang paling serem itu kalau waktu terasa nggak jalan.'`,
    `💬 Kamu: 'Tidur nyenyak ga?'\n👤 Napi L: 'Kadang nyenyak, kadang kebangun karena suara dari luar.'`,
    `💬 Kamu: 'Kapan terakhir dijenguk?'\n👤 Napi M: 'Sudah lama. Keluarga jauh dan susah datang.'`,
    `💬 Kamu: 'Kerja apa di sini?'\n👤 Napi N: 'Bantu bersihin dan kadang kerja di dapur.'`,
    `💬 Kamu: 'Takut ga?'\n👤 Napi O: 'Awal-awal iya. Lama-lama belajar beradaptasi.'`,
    `💬 Kamu: 'Ada yang baik ga di sini?'\n👤 Napi P: 'Banyak. Cuma nggak semuanya gampang percaya sama orang baru.'`,
    `💬 Kamu: 'Rencana abis keluar?'\n👤 Napi Q: 'Cari kerja dan mulai hidup dari awal.'`,
    `💬 Kamu: 'Pernah berantem?'\n👤 Napi R: 'Pernah ribut kecil. Sekarang lebih pilih menghindar.'`,
    `💬 Kamu: 'Doain gue ya.'\n👤 Napi S: 'Aamiin. Semoga urusan lu juga cepat selesai.'`,
    `💬 Kamu: 'Ini penjara atau hotel?'\n👤 Napi T: 'Hotel bintang nol. Bedanya di sini checkout-nya nggak bisa sesuka hati.'`,
    `💬 Kamu: 'Lu udah berapa lama di sini?'\n👤 Napi U: 'Lumayan lama. Sampai hafal suara langkah sipir.'`,
    `💬 Kamu: 'Kalau malam biasanya ngapain?'\n👤 Napi V: 'Baca, ngobrol pelan, atau langsung tidur.'`,
    `💬 Kamu: 'Ada yang bisa bikin ketawa di sini?'\n👤 Napi W: 'Ada. Tinggal denger cerita orang-orang di blok ini.'`,
    `💬 Kamu: 'Lu masih sering kepikiran kejadian dulu?'\n👤 Napi X: 'Sering. Tapi sekarang lebih banyak mikirin apa yang harus gue lakukan setelah keluar.'`,
    `💬 Kamu: 'Kalau dapat kesempatan belajar, mau?'\n👤 Napi Y: 'Mau banget. Biar waktu di sini nggak sia-sia.'`,
    `💬 Kamu: 'Paling susah di sini apa?'\n👤 Napi Z: 'Nahan rindu sama orang rumah.'`,
    `💬 Kamu: 'Lu punya teman dekat di sini?'\n👤 Napi A: 'Ada beberapa. Kalau susah, biasanya saling bantu.'`,
    `💬 Kamu: 'Kalau lagi sedih biasanya ngapain?'\n👤 Napi B: 'Diam sebentar, terus cari teman buat ngobrol.'`,
    `💬 Kamu: 'Pernah dapat kiriman dari rumah?'\n👤 Napi C: 'Sering. Makanan sederhana pun rasanya beda kalau dari rumah.'`,
    `💬 Kamu: 'Apa yang paling lu kangenin?'\n👤 Napi D: 'Suasana pagi di rumah. Kedengarannya sepele, tapi gue kangen.'`,
    `💬 Kamu: 'Di sini ada olahraga?'\n👤 Napi E: 'Ada. Biasanya lari, senam, atau olahraga ringan.'`,
    `💬 Kamu: 'Lu masih punya cita-cita?'\n👤 Napi F: 'Masih. Penjara bukan berarti hidup berhenti selamanya.'`,
    `💬 Kamu: 'Kalau dikasih satu makanan dari luar, mau apa?'\n👤 Napi G: 'Masakan ibu. Apa aja, yang penting buatan rumah.'`,
    `💬 Kamu: 'Pernah nangis di sini?'\n👤 Napi H: 'Pernah. Nggak ada yang perlu malu soal itu.'`,
    `💬 Kamu: 'Lu punya buku favorit?'\n👤 Napi I: 'Ada satu novel lama. Udah gue baca sampai beberapa kali.'`,
    `💬 Kamu: 'Hal paling lucu yang pernah terjadi di sini apa?'\n👤 Napi J: 'Teman gue salah pakai sandal orang sampai setengah hari.'`,
    `💬 Kamu: 'Kalau waktu bisa dipercepat, mau?'\n👤 Napi K: 'Siapa yang nggak mau? Tapi tetap harus dijalani.'`,
    `💬 Kamu: 'Lu pernah bantu napi lain?'\n👤 Napi L: 'Pernah. Kadang hal kecil aja sudah cukup membantu.'`,
    `💬 Kamu: 'Kalau ada yang baru masuk, biasanya gimana?'\n👤 Napi M: 'Dikasih tahu aturan dan dibantu adaptasi.'`,
    `💬 Kamu: 'Apa yang paling berubah dari diri lu?'\n👤 Napi N: 'Gue jadi lebih menghargai waktu dan keluarga.'`,
    `💬 Kamu: 'Kalau keluar nanti mau langsung pulang?'\n👤 Napi O: 'Pasti. Rumah adalah tempat pertama yang mau gue datangi.'`,
    `💬 Kamu: 'Pernah dapat kabar baik dari luar?'\n👤 Napi P: 'Pernah. Kabar kecil aja bisa bikin satu hari terasa lebih ringan.'`,
    `💬 Kamu: 'Kalau lagi marah gimana?'\n👤 Napi Q: 'Biasanya gue diam dulu daripada bikin masalah baru.'`,
    `💬 Kamu: 'Ada yang ngajarin keterampilan di sini?'\n👤 Napi R: 'Ada. Gue pernah diajarin bikin kerajinan dari kayu.'`,
    `💬 Kamu: 'Lu masih sering ketawa?'\n👤 Napi S: 'Masih dong. Kalau berhenti ketawa, hari-hari di sini makin berat.'`,
    `💬 Kamu: 'Kalau dikasih kesempatan ngomong sama keluarga sekarang, mau bilang apa?'\n👤 Napi T: 'Gue baik-baik aja dan minta mereka jangan terlalu khawatir.'`,
    `💬 Kamu: 'Apa yang paling bikin lu kuat?'\n👤 Napi U: 'Pikiran kalau suatu hari nanti gue bakal keluar dan mulai lagi.'`,
    `💬 Kamu: 'Pernah merasa waktu nggak bergerak?'\n👤 Napi V: 'Sering. Tapi begitu ada kegiatan, tiba-tiba hari sudah malam.'`,
    `💬 Kamu: 'Kalau bisa kasih nasihat ke diri lu yang dulu, apa?'\n👤 Napi W: 'Jangan ambil keputusan saat emosi.'`,
    `💬 Kamu: 'Besok mau ngapain?'\n👤 Napi X: 'Sama seperti biasa. Bangun, makan, kerja, ngobrol, lalu tidur.'`,
    `💬 Kamu: 'Lu masih berharap semuanya bisa diperbaiki?'\n👤 Napi Y: 'Masih. Selama masih hidup, selalu ada kesempatan buat berubah.'`
]
