export const REHABILITATION_ACTIVITY_STORIES = Object.freeze({

  kerja: [
    '🛠️ Kamu membantu merapikan ruang rehabilitasi dan menyelesaikan tugas dengan tekun.',
    '🌿 Kamu mendapat tugas membersihkan taman. Keringat bercucuran, tapi pekerjaan selesai.',
    '📦 Kamu membantu petugas menyusun perlengkapan dan belajar bertanggung jawab.',
    '🎨 Kamu mengecat bangku taman yang kusam sampai terlihat lebih rapi.',
    '🍳 Kamu membantu menyiapkan kebutuhan dapur dan bekerja sama dengan peserta lain.',
    '🧹 Kamu membantu membersihkan halaman dan memastikan tidak ada sampah yang tersisa.',
    '📋 Kamu dipercaya mengatur perlengkapan kerja dan menyelesaikan tugas tepat waktu.',
    '🔧 Kamu membantu memperbaiki beberapa fasilitas sederhana yang mulai rusak.',
    '📚 Kamu menyusun barang-barang gudang agar lebih mudah ditemukan.',
    '🏠 Kamu membantu menyiapkan ruangan sebelum kegiatan dimulai.',
    '🪟 Kamu membersihkan jendela dan membuat ruangan terlihat lebih terang.',
    '💪 Kamu membantu membawa perlengkapan tanpa mengeluh meski cukup berat.',
    '🪑 Kamu merapikan meja dan kursi setelah kegiatan selesai.',
    '📝 Kamu membantu petugas mencatat barang yang masuk dan keluar.',
    '🍽️ Kamu membersihkan area makan setelah semua orang selesai makan.',
    '🌱 Kamu membantu menata tanaman di sekitar halaman rehabilitasi.',
    '📦 Kamu mendapat pekerjaan tambahan dan tetap menyelesaikannya dengan baik.',
    '🔨 Kamu membantu memperbaiki pagar yang mulai terlihat rusak.',
    '🧹 Kamu membersihkan ruang penyimpanan dan menemukan banyak barang yang berantakan.',
    '🧰 Kamu membantu menyiapkan alat-alat untuk kegiatan hari ini.',
    '🤝 Kamu bekerja bersama peserta lain tanpa mempermasalahkan tugas yang diberikan.',
    '🛠️ Kamu belajar menggunakan peralatan kerja dengan benar dari pembimbing.',
    '🧽 Kamu membantu mengepel lantai hingga seluruh ruangan kembali bersih.',
    '📌 Kamu bertanggung jawab memastikan tempat kerja tetap tertata.',
    '📦 Kamu membantu memindahkan barang ke tempat yang sudah ditentukan.',
    '🧹 Kamu membersihkan meja kerja dan mengembalikan semua alat ke tempatnya.',
    '🎨 Kamu membantu mengecat dinding yang mulai kusam.',
    '🤝 Kamu menyelesaikan pekerjaan lebih awal lalu membantu peserta lain.',
    '🧹 Kamu dipercaya mengurus kebersihan salah satu area dan menjalankannya dengan baik.',
    '🥕 Kamu membantu menyiapkan bahan makanan untuk kegiatan bersama.',
    '🍂 Kamu membersihkan halaman setelah hujan membuat banyak daun berserakan.',
    '📅 Kamu membantu menyusun jadwal pekerjaan bersama pembimbing.',
    '🔧 Kamu memperbaiki rak sederhana yang hampir roboh.',
    '📚 Kamu membantu merapikan perpustakaan kecil di tempat rehabilitasi.',
    '⏰ Kamu menyelesaikan pekerjaan rutin tanpa harus terus diingatkan.',
    '🏋️ Kamu membantu mengangkat dan menata peralatan olahraga.',
    '🧹 Kamu membersihkan lorong dan memastikan jalannya tidak terhalang.',
    '🪑 Kamu membantu menyiapkan kursi untuk kegiatan kelompok.',
    '💧 Kamu merawat tanaman dan menyiramnya sebelum kegiatan dimulai.',
    '💡 Kamu belajar bahwa menyelesaikan pekerjaan kecil dengan baik juga membutuhkan tanggung jawab.',
    '🧹 Kamu membantu membersihkan fasilitas umum di sekitar tempat rehabilitasi.',
    '📦 Kamu menyusun perlengkapan berdasarkan jenisnya agar lebih teratur.',
    '🔨 Kamu membantu memperbaiki meja yang kakinya mulai longgar.',
    '⏱️ Kamu menjalankan tugas harian dengan disiplin tanpa mencari alasan.',
    '🧽 Kamu membantu membersihkan area setelah kegiatan bersama selesai.',
    '🔎 Kamu dipercaya memeriksa kebersihan beberapa ruangan.',
    '📋 Kamu membantu menyiapkan kebutuhan untuk kegiatan besok.',
    '💪 Kamu bekerja dengan tenang dan tidak mudah menyerah ketika menemui kesulitan.',
    '✅ Kamu menyelesaikan semua tugas yang diberikan sebelum waktu istirahat.',
    '🌱 Kamu mulai terbiasa menjalankan pekerjaan dengan penuh tanggung jawab.'
  ],

  sosial: [
    '💬 Kamu menemani peserta lain berbincang dan mendengarkan ceritanya dengan sabar.',
    '🤝 Kamu ikut kerja bakti bersama warga dan berkenalan dengan tetangga baru.',
    '🍱 Kamu membantu membagikan makanan kepada orang-orang di sekitar.',
    '🙏 Kamu meminta maaf atas kesalahan lama dan berusaha memperbaiki hubungan.',
    '🤝 Kamu bekerja sama dalam kegiatan kelompok dan belajar menghargai pendapat.',
    '👋 Kamu menyapa warga sekitar dan mendapat sambutan yang cukup baik.',
    '📦 Kamu membantu seseorang membawa barang tanpa mengharapkan imbalan.',
    '🧹 Kamu ikut membersihkan lingkungan bersama masyarakat sekitar.',
    '👂 Kamu mendengarkan keluhan peserta lain tanpa langsung menghakimi.',
    '👥 Kamu ikut kegiatan kelompok dan berusaha lebih terbuka kepada orang lain.',
    '🎁 Kamu membantu membagikan kebutuhan kepada peserta yang membutuhkan.',
    '💬 Kamu belajar menyampaikan pendapat tanpa memaksakan kehendak.',
    '🗣️ Kamu mengajak peserta lain berdiskusi untuk menyelesaikan masalah bersama.',
    '🤲 Kamu membantu seorang peserta yang kesulitan mengikuti kegiatan.',
    '⚖️ Kamu belajar menghargai perbedaan pendapat dalam sebuah diskusi.',
    '🏘️ Kamu ikut kegiatan warga dan mencoba membangun kembali kepercayaan.',
    '🕊️ Kamu berbicara dengan tenang ketika terjadi perbedaan pendapat.',
    '😊 Kamu membantu membuat suasana kelompok menjadi lebih nyaman.',
    '🙏 Kamu mengucapkan terima kasih kepada orang yang telah membantumu.',
    '👂 Kamu berusaha mendengarkan orang lain sebelum memberikan tanggapan.',
    '🍽️ Kamu ikut makan bersama peserta lain dan berbincang dengan santai.',
    '🤝 Kamu membantu menyelesaikan kesalahpahaman tanpa memperkeruh keadaan.',
    '🙋 Kamu menawarkan bantuan kepada peserta yang sedang kesulitan.',
    '🏘️ Kamu ikut kegiatan lingkungan dan menyelesaikan tugas bersama warga.',
    '💭 Kamu belajar bahwa kepercayaan dibangun dari tindakan kecil yang konsisten.',
    '👋 Kamu menyapa beberapa warga yang sebelumnya masih merasa canggung kepadamu.',
    '🗣️ Kamu ikut berdiskusi dan menerima kritik tanpa langsung tersinggung.',
    '🫂 Kamu membantu menenangkan peserta lain yang sedang emosi.',
    '👂 Kamu berusaha menjadi pendengar yang baik dalam percakapan hari ini.',
    '🎉 Kamu ikut menyiapkan kegiatan bersama dan membantu memastikan semuanya berjalan lancar.',
    '🙇 Kamu mengakui kesalahan saat terjadi masalah dalam kelompok.',
    '🤲 Kamu belajar meminta bantuan dengan cara yang baik ketika membutuhkannya.',
    '👋 Kamu membantu peserta baru beradaptasi dengan lingkungan rehabilitasi.',
    '👥 Kamu ikut kegiatan bersama tanpa memilih-milih siapa yang harus diajak bekerja sama.',
    '💪 Kamu memberikan semangat kepada peserta lain yang sedang kehilangan motivasi.',
    '🏘️ Kamu berbicara dengan warga sekitar dan perlahan mengurangi rasa canggung.',
    '🕊️ Kamu belajar menyelesaikan konflik melalui percakapan yang tenang.',
    '🛡️ Kamu membantu menjaga suasana tetap kondusif ketika diskusi mulai memanas.',
    '❤️ Kamu ikut kegiatan sosial dan menyadari pentingnya saling membantu.',
    '📝 Kamu menerima masukan dari orang lain dan mencoba memperbaikinya.',
    '👥 Kamu mengajak peserta lain melakukan kegiatan bersama agar tidak merasa sendirian.',
    '😊 Kamu membantu menghibur seseorang yang sedang mengalami hari buruk.',
    '🙏 Kamu belajar bahwa meminta maaf tidak membuat seseorang menjadi lebih rendah.',
    '🤝 Kamu menunjukkan sikap sopan kepada warga dan petugas sepanjang kegiatan.',
    '🏘️ Kamu ikut membantu persiapan acara lingkungan bersama masyarakat.',
    '🔄 Kamu berusaha tidak mengulangi sikap buruk yang pernah membuat orang lain kecewa.',
    '💬 Kamu membangun komunikasi yang lebih baik dengan orang-orang di sekitarmu.',
    '🤝 Kamu belajar mempercayai orang lain secara perlahan.',
    '🌱 Kamu mulai merasa diterima kembali setelah menunjukkan perubahan secara konsisten.'
  ],

  ibadah: [
    '🙏 Kamu meluangkan waktu untuk beribadah dan menenangkan pikiran.',
    '🕊️ Kamu mengikuti kegiatan rohani bersama dan pulang dengan hati lebih tenteram.',
    '🤲 Kamu berdoa, merenungkan kesalahan, lalu bertekad memperbaiki diri.',
    '📖 Kamu membaca kitab suci dengan khusyuk dan mengambil pelajaran darinya.',
    '🕌 Kamu membantu menyiapkan tempat ibadah sebelum mengikuti kegiatan bersama.',
    '🙏 Kamu meluangkan waktu untuk berdoa setelah menyelesaikan aktivitas hari ini.',
    '🕊️ Kamu mengikuti kegiatan keagamaan bersama peserta lain dengan tenang.',
    '💭 Kamu merenungkan keputusan buruk yang pernah dibuat dan ingin memperbaikinya.',
    '🧹 Kamu membantu membersihkan area tempat ibadah sebelum kegiatan dimulai.',
    '🌿 Kamu belajar untuk lebih sabar melalui waktu yang kamu gunakan untuk beribadah.',
    '📖 Kamu mengikuti pembinaan rohani dan mendengarkan nasihat dengan baik.',
    '🧘 Kamu mengambil waktu untuk menenangkan pikiran dan mengintrospeksi diri.',
    '📖 Kamu membaca kitab suci dan menemukan nasihat yang membuatmu berpikir.',
    '🕌 Kamu membantu menyiapkan perlengkapan untuk kegiatan keagamaan.',
    '🤲 Kamu berdoa agar diberi kekuatan untuk menjalani proses perubahan.',
    '🕊️ Kamu mengikuti kegiatan rohani tanpa banyak bicara dan menikmati suasananya.',
    '💭 Kamu merenungkan dampak dari tindakanmu terhadap orang lain.',
    '🧹 Kamu membantu merapikan tempat ibadah setelah kegiatan selesai.',
    '🌱 Kamu belajar memaafkan diri sendiri sambil tetap bertanggung jawab atas kesalahan.',
    '📝 Kamu mengikuti sesi renungan dan mencatat hal yang ingin kamu ubah.',
    '❤️ Kamu meluangkan waktu untuk bersyukur atas kesempatan memperbaiki diri.',
    '🤲 Kamu membantu peserta lain menyiapkan kegiatan rohani.',
    '🙏 Kamu berdoa dalam keheningan dan mencoba memahami kesalahan masa lalu.',
    '📖 Kamu mengikuti ceramah keagamaan dan mengambil pesan positif darinya.',
    '🧘 Kamu belajar mengendalikan emosi melalui refleksi dan ketenangan.',
    '🧹 Kamu membersihkan area sekitar tempat ibadah bersama peserta lain.',
    '🤲 Kamu mengikuti kegiatan doa bersama dengan penuh perhatian.',
    '💭 Kamu merenungkan arti tanggung jawab setelah mendengar nasihat pembimbing.',
    '📖 Kamu membaca kembali catatan renungan dan memikirkan perubahan yang sudah terjadi.',
    '🪑 Kamu membantu menyiapkan tempat duduk untuk kegiatan keagamaan.',
    '🙏 Kamu meluangkan waktu untuk meminta ampun dan berkomitmen tidak mengulangi kesalahan.',
    '🕊️ Kamu mengikuti kegiatan rohani dengan pikiran yang lebih terbuka.',
    '🌱 Kamu belajar bahwa perubahan membutuhkan kesabaran dan ketekunan.',
    '🧹 Kamu membantu membersihkan perlengkapan setelah kegiatan selesai.',
    '👂 Kamu mendengarkan pengalaman orang lain dan mengambil pelajaran darinya.',
    '💭 Kamu menggunakan waktu tenang untuk memikirkan masa depan setelah rehabilitasi.',
    '🤲 Kamu berdoa untuk orang-orang yang pernah terkena dampak dari kesalahanmu.',
    '📖 Kamu mengikuti kegiatan pembinaan dengan sikap yang lebih serius.',
    '🌅 Kamu merenungkan hal-hal baik yang ingin kamu lakukan setelah bebas.',
    '🕌 Kamu membantu menjaga kebersihan tempat ibadah selama kegiatan berlangsung.',
    '🧘 Kamu belajar mengendalikan diri dengan meluangkan waktu untuk refleksi.',
    '🙏 Kamu mengikuti doa bersama dan merasa pikiranmu menjadi lebih tenang.',
    '📖 Kamu membaca kitab suci dan menemukan pengingat tentang pentingnya berbuat baik.',
    '🕊️ Kamu mengikuti kegiatan rohani bersama tanpa mengganggu peserta lain.',
    '💭 Kamu menggunakan waktu ibadah untuk mengevaluasi sikapmu selama ini.',
    '🤲 Kamu membantu peserta lain menyiapkan kebutuhan kegiatan keagamaan.',
    '🌱 Kamu belajar menerima masa lalu tanpa menjadikannya alasan untuk berbuat buruk lagi.',
    '🙏 Kamu berdoa untuk diberi kesempatan membangun kembali kepercayaan.',
    '🕊️ Kamu menutup kegiatan hari ini dengan doa dan niat untuk menjadi lebih baik.'
  ],

  olahraga: [
    '🏃 Kamu jogging mengelilingi lapangan dan menyelesaikan latihan dengan semangat.',
    '🤸 Kamu mengikuti senam pagi bersama peserta lain.',
    '🏸 Kamu bermain bulu tangkis santai sambil menjaga sportivitas.',
    '🧘 Kamu berlatih peregangan dan latihan ringan agar tubuh lebih bugar.',
    '🚶 Kamu berjalan kaki di taman sambil menikmati udara segar.',
    '🔥 Kamu melakukan pemanasan sebelum mengikuti latihan pagi.',
    '🏃 Kamu berlari beberapa putaran dan berhasil menyelesaikannya tanpa menyerah.',
    '💪 Kamu mengikuti latihan kebugaran bersama peserta lain.',
    '⚽ Kamu bermain sepak bola dan belajar tetap sportif meski kalah.',
    '🏋️ Kamu melakukan latihan kekuatan ringan sesuai arahan pembimbing.',
    '🚶 Kamu berjalan santai sambil berbincang dengan peserta lain.',
    '🏀 Kamu mencoba olahraga baru yang sebelumnya belum pernah kamu lakukan.',
    '🏃 Kamu mengikuti latihan pagi dan berusaha menyelesaikan setiap gerakan.',
    '🏓 Kamu bermain tenis meja bersama peserta lain dengan suasana santai.',
    '🧘 Kamu melakukan pendinginan setelah latihan agar tubuh tidak terlalu lelah.',
    '🏋️ Kamu membantu menyiapkan peralatan olahraga sebelum latihan dimulai.',
    '🏆 Kamu ikut pertandingan kecil dan belajar menerima hasil dengan lapang dada.',
    '🌬️ Kamu melakukan latihan pernapasan untuk membantu menjaga ketenangan.',
    '🏀 Kamu bermain basket bersama peserta lain dan bekerja sama dalam tim.',
    '💪 Kamu menyelesaikan latihan meski sempat merasa ingin berhenti.',
    '🚶 Kamu berjalan mengelilingi lingkungan rehabilitasi untuk menjaga kebugaran.',
    '🤸 Kamu mengikuti latihan ringan bersama kelompok pagi ini.',
    '⚖️ Kamu belajar menjaga sportivitas saat bermain bersama orang lain.',
    '🧘 Kamu melakukan peregangan setelah bangun tidur agar tubuh lebih siap beraktivitas.',
    '👥 Kamu mengikuti permainan kelompok dan membantu timmu bekerja sama.',
    '🏐 Kamu bermain voli dan belajar menghargai kemampuan peserta lain.',
    '🏃 Kamu melakukan latihan fisik sederhana secara rutin.',
    '🧹 Kamu membantu membereskan peralatan olahraga setelah latihan.',
    '📈 Kamu mencoba meningkatkan kemampuan lari sedikit demi sedikit.',
    '☀️ Kamu mengikuti olahraga pagi meski cuaca terasa cukup panas.',
    '🏸 Kamu bermain bulu tangkis dan tetap menjaga sikap sportif saat pertandingan.',
    '⚖️ Kamu melakukan latihan keseimbangan untuk meningkatkan koordinasi tubuh.',
    '🌳 Kamu berjalan kaki bersama kelompok sambil menikmati suasana pagi.',
    '🤝 Kamu mengikuti latihan bersama dan memberi semangat kepada peserta lain.',
    '⏱️ Kamu belajar bahwa latihan rutin membutuhkan kedisiplinan.',
    '🏃 Kamu menyelesaikan beberapa putaran lari tanpa berhenti di tengah jalan.',
    '🏅 Kamu mengikuti permainan olahraga tanpa mempermasalahkan siapa yang menang.',
    '🤝 Kamu membantu peserta lain memahami aturan permainan.',
    '💪 Kamu melakukan latihan ringan setelah merasa tubuh mulai lebih bugar.',
    '⚽ Kamu mengikuti olahraga kelompok dan belajar mengendalikan emosi saat bertanding.',
    '📈 Kamu mencoba memperbaiki catatan latihanmu dibanding hari sebelumnya.',
    '🧘 Kamu melakukan pendinginan bersama setelah latihan selesai.',
    '⚽ Kamu bermain sepak bola dan memilih tetap sportif ketika terjadi pelanggaran.',
    '🌅 Kamu mengikuti jalan pagi untuk menjaga tubuh tetap aktif.',
    '🏋️ Kamu membantu membawa peralatan olahraga ke tempat penyimpanan.',
    '🔥 Kamu mengikuti latihan fisik dengan konsisten meski hasilnya belum sempurna.',
    '⏰ Kamu belajar menjaga disiplin melalui rutinitas olahraga.',
    '😮‍💨 Kamu menyelesaikan latihan hari ini dengan tubuh lelah tetapi pikiran lebih segar.',
    '🌱 Kamu mulai menikmati rutinitas olahraga sebagai bagian dari perubahan hidupmu.'
  ],

  belajar: [
    '📚 Kamu mengikuti kelas keterampilan dan berhasil memahami materi baru.',
    '📖 Kamu membaca buku pengembangan diri dan mencatat hal yang ingin diterapkan.',
    '💰 Kamu belajar mengelola keuangan agar lebih bijak setelah bebas.',
    '🛠️ Kamu berlatih keterampilan kerja bersama pembimbing.',
    '💭 Kamu berdiskusi tentang cara mengambil keputusan yang lebih baik.',
    '🧠 Kamu mengikuti pelajaran tentang cara mengendalikan emosi.',
    '📝 Kamu belajar membuat rencana hidup setelah menyelesaikan rehabilitasi.',
    '📖 Kamu membaca buku tentang komunikasi dan mencoba menerapkan isinya.',
    '🎓 Kamu mengikuti pelatihan keterampilan yang bisa digunakan untuk mencari pekerjaan.',
    '⏰ Kamu belajar mengatur waktu agar kegiatan sehari-hari lebih teratur.',
    '💭 Kamu berdiskusi tentang dampak tindakan kriminal terhadap orang lain.',
    '🕊️ Kamu mempelajari cara menyelesaikan masalah tanpa menggunakan kekerasan.',
    '💻 Kamu mengikuti kelas komputer dan mencoba memahami materi baru.',
    '💰 Kamu belajar membuat anggaran sederhana untuk mengatur pengeluaran.',
    '📚 Kamu membaca materi tentang tanggung jawab dan mencatat hal penting.',
    '🗣️ Kamu berlatih berbicara dengan lebih tenang saat menghadapi perbedaan pendapat.',
    '🛠️ Kamu mengikuti pelatihan kerja dan mencoba menyelesaikan tugas yang diberikan.',
    '🔄 Kamu belajar mengenali kebiasaan buruk yang perlu diubah.',
    '💬 Kamu berdiskusi dengan pembimbing tentang rencana masa depan.',
    '📖 Kamu membaca buku tentang pengembangan diri dan menemukan beberapa hal yang relevan.',
    '🧠 Kamu belajar membuat keputusan berdasarkan pertimbangan, bukan emosi sesaat.',
    '📝 Kamu mengikuti kelas keterampilan dasar dan berhasil menyelesaikan latihan.',
    '💼 Kamu mempelajari cara mencari pekerjaan setelah masa rehabilitasi selesai.',
    '🤝 Kamu belajar pentingnya menepati janji dan menyelesaikan tanggung jawab.',
    '🏘️ Kamu mengikuti diskusi tentang cara membangun kembali kepercayaan masyarakat.',
    '💰 Kamu belajar mengatur penghasilan agar tidak kembali pada kebiasaan lama.',
    '🛠️ Kamu berlatih keterampilan baru yang sebelumnya tidak pernah kamu kuasai.',
    '🗣️ Kamu mengikuti kelas tentang komunikasi dan belajar mendengarkan dengan baik.',
    '📖 Kamu membaca pengalaman orang lain yang berhasil mengubah hidupnya.',
    '⚠️ Kamu belajar mengenali situasi yang bisa memicu perilaku buruk.',
    '💬 Kamu berdiskusi tentang cara menghadapi tekanan dari lingkungan.',
    '🎓 Kamu mengikuti pelatihan dan meminta bantuan ketika tidak memahami materi.',
    '🌱 Kamu belajar bahwa kesalahan masa lalu tidak harus menentukan masa depan.',
    '📝 Kamu membuat daftar tujuan yang ingin dicapai setelah kembali ke masyarakat.',
    '🛠️ Kamu mempelajari keterampilan sederhana yang bisa menjadi sumber penghasilan.',
    '👨‍👩‍👦 Kamu mengikuti sesi pembelajaran tentang tanggung jawab terhadap keluarga.',
    '🤝 Kamu belajar cara menyelesaikan konflik melalui komunikasi.',
    '📚 Kamu membaca materi tentang pentingnya menjaga kepercayaan orang lain.',
    '🙋 Kamu mengikuti kelas dan berusaha aktif menjawab pertanyaan.',
    '🧘 Kamu mempelajari cara mengelola stres tanpa melampiaskannya kepada orang lain.',
    '📅 Kamu belajar menyusun jadwal harian agar hidup lebih teratur.',
    '💬 Kamu berdiskusi dengan peserta lain tentang pengalaman dan pelajaran hidup.',
    '🎓 Kamu mengikuti pelatihan kerja dan mendapat masukan dari pembimbing.',
    '🌱 Kamu belajar bahwa perubahan membutuhkan usaha yang dilakukan secara konsisten.',
    '📖 Kamu membaca materi tentang kehidupan setelah rehabilitasi dan membuat rencana sederhana.',
    '🧠 Kamu mempelajari cara menghadapi masalah tanpa mengambil jalan pintas.',
    '📝 Kamu mengikuti kelas dengan serius dan menyelesaikan tugas yang diberikan.',
    '🔄 Kamu mulai memahami kebiasaan apa saja yang perlu dipertahankan setelah bebas.',
    '🌅 Kamu menyelesaikan kegiatan belajar hari ini dengan beberapa pelajaran baru untuk masa depan.'
  ]

})
