const CRIME_STORIES = Object.freeze({
  copet: {
    success: [
      'Di tengah keramaian, tanganmu bergerak cepat sebelum korban menyadarinya.',
      'Kamu memanfaatkan kelengahan sesaat dan menghilang di antara orang-orang.',
      'Dengan gerakan cekatan, barang berharga berpindah tangan tanpa menarik perhatian.',
      'Keramaian menjadi kesempatan; kamu berhasil mengambil barang tanpa diketahui.',
      'Korban sibuk memperhatikan sekitar saat kamu berhasil mengambil barangnya.',
      'Kamu bergerak mengikuti arus kerumunan dan berhasil mengambil barang berharga.',
      'Dalam suasana yang padat, aksimu berlangsung tanpa menimbulkan kecurigaan.',
      'Kamu menemukan celah di tengah keramaian dan berhasil melancarkan aksimu.',
      'Perhatian korban teralihkan sesaat dan kamu memanfaatkan kesempatan itu.',
      'Kamu berhasil mengambil barang sebelum korban menyadari sesuatu yang hilang.',
      'Kerumunan membuat gerakanmu sulit diperhatikan dan aksimu berjalan lancar.',
      'Kamu menunggu momen yang tepat lalu bergerak cepat meninggalkan lokasi.',
      'Barang berharga berhasil kamu ambil sebelum korban menyadari kejanggalan.',
      'Kamu berpura-pura menjadi bagian dari kerumunan hingga berhasil mendapatkan barang.',
      'Kesempatan datang saat korban lengah dan kamu berhasil memanfaatkannya.',
      'Dengan langkah tenang, kamu mengambil barang lalu menyatu kembali dengan kerumunan.',
      'Kamu berhasil melakukan aksimu di tengah suasana yang ramai.',
      'Korban terlalu sibuk dengan urusannya sehingga tidak menyadari aksimu.',
      'Kamu bergerak cepat saat perhatian semua orang tertuju ke arah lain.',
      'Barang target berhasil berpindah tangan tanpa membuat suasana berubah.',
      'Kamu berhasil menemukan celah di antara orang-orang dan melancarkan aksimu.',
      'Aksimu berlangsung singkat dan korban baru menyadari kehilangan setelah kamu pergi.',
      'Kamu mengikuti kerumunan sampai menemukan kesempatan yang tepat.',
      'Dengan timing yang pas, kamu berhasil mengambil barang target.',
      'Kamu bergerak tanpa banyak menarik perhatian dan berhasil meninggalkan tempat.',
      'Suasana ramai membuat keberadaanmu tidak terlalu diperhatikan.',
      'Kamu memanfaatkan antrean panjang untuk menjalankan aksimu.',
      'Perhatian korban terpecah oleh keributan kecil dan kamu langsung bertindak.',
      'Kamu berhasil mengambil barang lalu berpindah tempat sebelum dicurigai.',
      'Gerakan cepatmu membuat korban tidak sempat menyadari apa yang terjadi.',
      'Kamu memanfaatkan kepadatan tempat untuk menjalankan aksimu dengan mulus.',
      'Target terlihat lengah dan kamu berhasil mengambil kesempatan tersebut.',
      'Kamu menunggu sampai suasana cukup ramai sebelum menjalankan aksimu.',
      'Barang berhasil kamu dapatkan dan kamu segera menjauh dari lokasi.',
      'Kamu berhasil bergerak di antara orang-orang tanpa menimbulkan kecurigaan.',
      'Korban tidak menyadari kehilangan barang sampai kamu sudah jauh.',
      'Kamu menemukan kesempatan singkat dan berhasil memanfaatkannya.',
      'Aksimu berjalan lancar karena perhatian orang-orang sedang teralihkan.',
      'Kamu berhasil mengambil barang target di tengah keramaian.',
      'Dengan gerakan singkat, barang target berhasil kamu dapatkan.',
      'Kamu berhasil memanfaatkan suasana ramai untuk menyembunyikan gerakanmu.',
      'Target terlalu fokus pada aktivitasnya sehingga tidak menyadari aksimu.',
      'Kamu bergerak cepat dan berhasil menghilang sebelum dicurigai.',
      'Keramaian membuatmu mudah menyatu kembali setelah mengambil barang.',
      'Kamu berhasil menjalankan aksimu tanpa membuat korban curiga.',
      'Kesempatan terbuka sesaat dan kamu langsung memanfaatkannya.',
      'Kamu berhasil mengambil barang saat target sedang tidak memperhatikan.',
      'Aksimu selesai sebelum ada yang menyadari keberadaanmu.',
      'Kamu berhasil memanfaatkan momen singkat di tengah kerumunan.',
      'Barang berharga berhasil kamu ambil dan kamu meninggalkan tempat dengan tenang.'
    ],
    failure: [
      'Korban menyadari gerakanmu dan orang-orang di sekitar langsung menoleh.',
      'Tanganmu tertangkap basah sebelum sempat mengambil apa pun.',
      'Aksimu terlihat oleh saksi; kamu terpaksa menyerahkan denda.',
      'Korban tiba-tiba berbalik dan langsung menyadari gerakanmu.',
      'Seorang saksi melihat gerakan mencurigakanmu dan memanggil petugas.',
      'Kamu terlalu lambat sehingga target menyadari barangnya hampir diambil.',
      'Kerumunan justru memperhatikan gerakanmu dan aksimu gagal.',
      'Korban merasakan sesuatu yang aneh sebelum kamu berhasil mengambil barang.',
      'Gerakanmu terlihat jelas dan beberapa orang mulai mengejarmu.',
      'Kamu kehilangan kesempatan setelah target tiba-tiba memeriksa barangnya.',
      'Seorang pejalan kaki melihat aksimu dan segera memberi tahu korban.',
      'Tanganmu hampir berhasil, tetapi korban langsung menghindar.',
      'Kamu salah memilih momen dan korban langsung menyadari keberadaanmu.',
      'Barang terjatuh sebelum berhasil kamu bawa pergi.',
      'Kamu tertangkap perhatian korban saat mencoba mengambil barang.',
      'Seorang saksi berada terlalu dekat dan melihat seluruh gerakanmu.',
      'Korban berteriak setelah menyadari barangnya sedang kamu ambil.',
      'Kamu panik ketika target tiba-tiba menoleh ke arahmu.',
      'Aksimu gagal karena korban menyimpan barang di tempat yang sulit dijangkau.',
      'Kamu membuat gerakan mencurigakan dan langsung diperhatikan orang sekitar.',
      'Target menyadari tanganmu sebelum aksimu selesai.',
      'Kamu kehilangan kesempatan ketika kerumunan mendadak menjadi sepi.',
      'Saksi menunjuk ke arahmu setelah melihat gerakan yang mencurigakan.',
      'Korban berhasil menjauh sebelum kamu sempat mengambil barang.',
      'Kamu ketahuan saat mencoba menyatu kembali dengan kerumunan.',
      'Gerakanmu terlalu mencolok sehingga beberapa orang langsung memperhatikan.',
      'Target merasakan barangnya disentuh dan segera menoleh.',
      'Kamu salah memperkirakan situasi dan aksimu terbongkar.',
      'Seorang petugas berada di dekat lokasi dan langsung menghampirimu.',
      'Barang target berhasil diamankan sebelum sempat kamu ambil.',
      'Kamu tertangkap basah setelah tanganmu menyentuh barang target.',
      'Korban langsung memeriksa barangnya dan menyadari ada yang mencurigakan.',
      'Kerumunan mendadak bergerak sehingga aksimu gagal.',
      'Kamu kehilangan keseimbangan dan menarik perhatian orang sekitar.',
      'Saksi melihat gerakanmu dari jarak dekat dan segera bereaksi.',
      'Korban berhasil menghindari tanganmu tepat sebelum barang diambil.',
      'Kamu terlalu terburu-buru dan membuat gerakan yang mencurigakan.',
      'Target tiba-tiba menghentikan langkah sehingga kamu gagal bertindak.',
      'Aksimu diketahui sebelum barang berhasil berpindah tangan.',
      'Kamu salah mengira seseorang sebagai target dan langsung ketahuan.',
      'Orang di sekitar menyadari gerakanmu dan suasana menjadi tegang.',
      'Korban langsung meminta bantuan setelah menyadari percobaanmu.',
      'Kamu gagal menyembunyikan gerakan dan menjadi pusat perhatian.',
      'Seorang saksi menghalangi gerakanmu sebelum berhasil mengambil barang.',
      'Target berhasil menjauh dan kamu kehilangan kesempatan.',
      'Kamu tertangkap saat mencoba mengambil barang dari sisi belakang target.',
      'Gerakanmu terbaca dan korban langsung mengamankan barangnya.',
      'Aksimu gagal karena tempat tersebut ternyata memiliki banyak saksi.',
      'Kamu tidak sempat mengambil apa pun sebelum orang sekitar menyadarinya.',
      'Korban berhasil mengenali gerakanmu dan meminta bantuan.'
    ]
  },
  begal: {
    success: [
      'Kamu menghadang target di jalan sepi dan berhasil membawa kabur uangnya.',
      'Aksi berlangsung cepat; target tak sempat meminta bantuan.',
      'Setelah mengambil uang target, kamu segera menghilang dari lokasi.',
      'Kamu berhasil menghentikan perjalanan target dan mengambil uangnya.',
      'Jalanan sepi membuat aksimu berjalan tanpa banyak gangguan.',
      'Target kehilangan kesempatan meminta bantuan dan kamu berhasil melarikan diri.',
      'Kamu menghadang kendaraan target dan berhasil mengambil barang berharganya.',
      'Aksimu berlangsung singkat sebelum kamu meninggalkan lokasi.',
      'Kamu memanfaatkan jalan yang sepi dan berhasil membawa hasil rampokan.',
      'Target terkejut dan tidak sempat melakukan perlawanan.',
      'Kamu berhasil menguasai situasi dan segera kabur membawa uang target.',
      'Aksi berlangsung cepat sebelum ada kendaraan lain yang lewat.',
      'Kamu menghadang target di tempat sepi dan berhasil mengambil barangnya.',
      'Target menyerahkan barang setelah kamu berhasil mengintimidasinya.',
      'Kamu berhasil membawa kabur uang sebelum bantuan datang.',
      'Jalanan yang lengang membuatmu mudah meninggalkan lokasi.',
      'Kamu menemukan target yang sedang sendirian dan berhasil melancarkan aksi.',
      'Target tidak sempat memanggil bantuan sebelum kamu pergi.',
      'Kamu berhasil mengambil uang dan segera menjauh dari lokasi.',
      'Aksi berlangsung tanpa gangguan hingga kamu berhasil kabur.',
      'Kamu memanfaatkan kondisi sekitar yang sepi untuk menjalankan aksimu.',
      'Target terkejut ketika kamu muncul dan tidak sempat bereaksi.',
      'Kamu berhasil membuat target menyerahkan barang berharganya.',
      'Setelah mendapatkan uang, kamu langsung meninggalkan tempat.',
      'Tidak ada orang di sekitar saat kamu berhasil menjalankan aksimu.',
      'Kamu berhasil menghadang target sebelum ia mencapai tempat ramai.',
      'Aksimu berjalan cepat dan target kehilangan kesempatan melawan.',
      'Kamu berhasil mengambil barang target dan melarikan diri.',
      'Target terlalu terkejut untuk meminta pertolongan.',
      'Kamu berhasil meninggalkan jalan tersebut sebelum bantuan tiba.',
      'Aksi berjalan sesuai rencana dan kamu membawa hasilnya pergi.',
      'Kamu memilih lokasi yang sepi dan berhasil menjalankan aksimu.',
      'Target akhirnya menyerahkan uang dan kamu segera kabur.',
      'Kamu berhasil menguasai situasi selama beberapa saat.',
      'Jalan yang kosong membuat pelarianmu berlangsung lancar.',
      'Kamu berhasil mengambil uang target tanpa gangguan dari orang lain.',
      'Target tidak sempat mengejar ketika kamu mulai melarikan diri.',
      'Kamu berhasil menghadang target dan membawa kabur barang berharganya.',
      'Aksi selesai sebelum ada orang yang datang membantu.',
      'Kamu memanfaatkan momen sepi untuk mendapatkan uang target.',
      'Target kehilangan barang berharganya dan kamu berhasil menjauh.',
      'Kamu berhasil menjalankan aksi di lokasi yang minim orang.',
      'Pelarianmu berlangsung lancar setelah mendapatkan uang target.',
      'Target tidak mampu menghentikanmu sebelum kamu meninggalkan lokasi.',
      'Kamu berhasil mengambil hasil aksi dan menghilang di ujung jalan.',
      'Situasi sekitar mendukung aksimu hingga kamu berhasil kabur.',
      'Kamu berhasil menghadang target dan mengambil uangnya.',
      'Aksi selesai dengan cepat sebelum situasi berubah.',
      'Kamu berhasil membawa kabur hasil aksi dari lokasi.',
      'Target baru menyadari keadaan setelah kamu sudah pergi.'
    ],
    failure: [
      'Target melawan dan keadaan berbalik hingga kamu tertembak.',
      'Aksimu gagal; bantuan datang sebelum kamu sempat kabur.',
      'Kamu tertangkap saat mencoba melarikan diri dari lokasi.',
      'Target berhasil berteriak dan menarik perhatian orang sekitar.',
      'Seorang pengendara lewat dan membuatmu kehilangan kesempatan.',
      'Target melakukan perlawanan hingga kamu terpaksa melarikan diri tanpa hasil.',
      'Bantuan datang lebih cepat dari perkiraanmu.',
      'Kamu salah memilih lokasi dan ternyata ada banyak orang di sekitar.',
      'Target berhasil menjauh sebelum kamu mendapatkan apa pun.',
      'Aksimu diketahui warga dan kamu terpaksa kabur dengan tangan kosong.',
      'Kamu kehilangan kendali atas situasi setelah target melawan.',
      'Sebuah kendaraan berhenti dan membuat rencanamu berantakan.',
      'Target berhasil meminta bantuan melalui telepon.',
      'Kamu tertangkap sebelum sempat membawa kabur uang target.',
      'Orang sekitar mendengar keributan dan segera mendekat.',
      'Target berhasil melawan dan membuatmu kehilangan kesempatan.',
      'Aksi gagal karena jalan tersebut ternyata tidak benar-benar sepi.',
      'Kamu melihat petugas mendekat dan terpaksa meninggalkan lokasi.',
      'Target berhasil melarikan diri sebelum kamu sempat mengambil uangnya.',
      'Keributan menarik perhatian warga dan aksimu terbongkar.',
      'Kamu gagal membuat target menyerahkan barangnya.',
      'Bantuan datang ketika aksimu baru saja dimulai.',
      'Target berhasil menghindar dan berteriak meminta pertolongan.',
      'Kamu salah memperkirakan jumlah orang di sekitar lokasi.',
      'Seorang saksi melihat aksimu dan langsung menghubungi polisi.',
      'Target berhasil mempertahankan barangnya dan melarikan diri.',
      'Kamu panik ketika suara kendaraan mendekat.',
      'Aksimu terhenti karena target melakukan perlawanan keras.',
      'Kamu tertangkap saat mencoba meninggalkan lokasi.',
      'Warga sekitar datang setelah mendengar suara keributan.',
      'Target berhasil menjauh sebelum kamu mendapatkan uangnya.',
      'Rencana pelarianmu gagal karena jalan keluar sudah ramai.',
      'Kamu kehilangan kesempatan ketika target tiba-tiba berteriak.',
      'Petugas datang tepat saat kamu hendak kabur.',
      'Target berhasil menghubungi orang lain dan membuatmu terdesak.',
      'Kamu gagal mengambil uang setelah target melakukan perlawanan.',
      'Kerumunan mulai terbentuk dan kamu terpaksa meninggalkan lokasi.',
      'Aksimu terbaca sejak awal sehingga target berhasil menghindar.',
      'Kamu tertahan di lokasi sampai bantuan datang.',
      'Target berhasil membuatmu kehilangan keseimbangan dan kabur.',
      'Kamu salah memilih target dan situasi langsung berubah.',
      'Suara alarm dari kendaraan target membuat orang berdatangan.',
      'Kamu gagal menguasai situasi dan harus melarikan diri tanpa hasil.',
      'Seorang warga menghadang jalanmu sehingga kamu kehilangan kesempatan.',
      'Target berhasil meminta pertolongan sebelum kamu pergi.',
      'Aksi gagal setelah beberapa orang mulai mengejarmu.',
      'Kamu tidak sempat mengambil apa pun karena target langsung melawan.',
      'Petugas tiba sebelum kamu berhasil meninggalkan lokasi.',
      'Target berhasil kabur dan kamu terpaksa pergi dengan tangan kosong.'
    ]
  },
  bunuh: {
    success: [
      'Seranganmu berhasil menjatuhkan target dan kamu membawa kabur sebagian uangnya.',
      'Target tak sempat menghindar; suasana di sekitar langsung menjadi panik.',
      'Aksimu berhasil, tetapi keributan membuatmu harus segera meninggalkan lokasi.',
      'Seranganmu mengenai target sebelum ia sempat bereaksi.',
      'Target tumbang dan kamu segera meninggalkan lokasi.',
      'Kamu berhasil melancarkan serangan dan mengambil uang target.',
      'Situasi berubah kacau setelah seranganmu berhasil.',
      'Target tidak sempat menghindar dari serangan yang kamu lancarkan.',
      'Aksimu berhasil dan kamu segera meninggalkan tempat kejadian.',
      'Kamu berhasil menjatuhkan target sebelum bantuan datang.',
      'Seranganmu berhasil membuat target tidak mampu melawan.',
      'Kamu mengambil sebagian uang target sebelum meninggalkan lokasi.',
      'Target kehilangan kesempatan untuk melarikan diri setelah seranganmu.',
      'Aksi berlangsung cepat dan kamu berhasil keluar dari lokasi.',
      'Kamu berhasil melancarkan serangan saat target lengah.',
      'Target tidak sempat menyadari serangan sebelum semuanya terlambat.',
      'Kamu berhasil menyelesaikan aksimu dan langsung melarikan diri.',
      'Seranganmu berhasil dan membuat suasana sekitar menjadi kacau.',
      'Target tumbang setelah seranganmu dan kamu segera pergi.',
      'Kamu berhasil mengambil uang target di tengah kekacauan.',
      'Aksimu berhasil sebelum orang-orang sekitar memahami apa yang terjadi.',
      'Target tidak mampu menghindari seranganmu.',
      'Kamu berhasil menjatuhkan target lalu meninggalkan lokasi.',
      'Keributan pecah setelah seranganmu berhasil.',
      'Kamu berhasil melancarkan serangan dan membawa sebagian hasilnya.',
      'Target terlambat menyadari bahaya hingga seranganmu berhasil.',
      'Kamu segera pergi setelah memastikan aksimu berhasil.',
      'Serangan berlangsung singkat dan target tidak sempat meminta bantuan.',
      'Kamu berhasil membuat target tumbang sebelum situasi berubah.',
      'Aksimu berhasil dan kamu meninggalkan tempat sebelum banyak orang datang.',
      'Target gagal menghindar dari serangan yang kamu lancarkan.',
      'Kamu berhasil mengambil sebagian uang target setelah serangan.',
      'Situasi menjadi panik tepat setelah aksimu berhasil.',
      'Kamu berhasil menyerang target dan segera mencari jalan keluar.',
      'Target tidak sempat melakukan perlawanan berarti.',
      'Seranganmu berhasil membuat target kehilangan kesempatan melarikan diri.',
      'Kamu berhasil menyelesaikan aksi sebelum bantuan datang.',
      'Target tumbang dan kamu langsung meninggalkan lokasi.',
      'Kamu berhasil memanfaatkan kelengahan target untuk menyerang.',
      'Aksimu berhasil meski keributan langsung terjadi setelahnya.',
      'Kamu berhasil membawa sebagian uang target sebelum kabur.',
      'Target tidak menyadari serangan sampai semuanya terjadi terlalu cepat.',
      'Kamu berhasil melancarkan serangan dan menjauh dari lokasi.',
      'Seranganmu berhasil dan orang-orang mulai panik.',
      'Target tidak sempat memanggil bantuan sebelum serangan berhasil.',
      'Kamu berhasil menjatuhkan target lalu melarikan diri.',
      'Aksimu berhasil meski keadaan sekitar mulai kacau.',
      'Kamu berhasil mengambil uang target setelah serangan.',
      'Target gagal menghindar dan kamu berhasil meninggalkan lokasi.',
      'Seranganmu berhasil sebelum ada yang sempat menghentikanmu.'
    ],
    failure: [
      'Target lebih sigap dan seranganmu berbalik mengenai dirimu.',
      'Rencanamu terbaca; kamu tumbang sebelum sempat menyerang.',
      'Kamu gagal melancarkan serangan dan tertangkap di tempat.',
      'Target berhasil menghindar tepat sebelum seranganmu mengenai sasaran.',
      'Kamu kehilangan kesempatan ketika target menyadari niatmu.',
      'Seranganmu meleset dan target langsung meminta bantuan.',
      'Target berhasil melawan sehingga aksimu gagal.',
      'Kamu tertangkap sebelum sempat menyelesaikan serangan.',
      'Rencanamu diketahui orang sekitar dan suasana langsung kacau.',
      'Target bergerak lebih cepat dan berhasil menghindari seranganmu.',
      'Kamu kehilangan kendali dan gagal menjatuhkan target.',
      'Seranganmu gagal setelah target melakukan perlawanan.',
      'Bantuan datang sebelum kamu sempat melancarkan serangan kedua.',
      'Target berhasil menjauh dan membuat aksimu berantakan.',
      'Kamu tertahan di lokasi setelah seranganmu gagal.',
      'Target berhasil membaca gerakanmu sejak awal.',
      'Seranganmu meleset dan menarik perhatian orang sekitar.',
      'Kamu gagal karena target tiba-tiba berbalik melawan.',
      'Petugas datang sebelum aksimu berhasil diselesaikan.',
      'Target berhasil meminta pertolongan setelah menghindari serangan.',
      'Kamu kehilangan kesempatan ketika target berlari menjauh.',
      'Rencana seranganmu gagal dan kamu terpaksa melarikan diri.',
      'Target berhasil menahan seranganmu dan membuatmu kewalahan.',
      'Aksimu diketahui saksi sebelum berhasil mengenai target.',
      'Kamu salah memperkirakan gerakan target dan seranganmu gagal.',
      'Target berhasil menghindar dan langsung mencari bantuan.',
      'Seranganmu tidak mengenai sasaran dan membuat target waspada.',
      'Kamu gagal menyerang sebelum orang lain datang.',
      'Target melawan dan membuatmu kehilangan kesempatan.',
      'Kamu tertangkap setelah gagal melancarkan serangan.',
      'Keributan menarik perhatian orang sekitar sebelum aksimu berhasil.',
      'Target berhasil kabur dari jangkauanmu.',
      'Seranganmu terbaca dan target langsung mengambil jarak.',
      'Kamu gagal menjatuhkan target setelah serangan pertama meleset.',
      'Bantuan tiba ketika kamu masih berada di lokasi.',
      'Target berhasil menghindari serangan dan meminta pertolongan.',
      'Kamu kehilangan kesempatan karena situasi berubah mendadak.',
      'Rencanamu berantakan setelah target melakukan perlawanan.',
      'Kamu gagal menyerang dan langsung menjadi sasaran pengejaran.',
      'Target berhasil menghindar tepat pada waktunya.',
      'Seranganmu meleset dan membuat semua orang di sekitar waspada.',
      'Kamu tidak sempat melanjutkan aksi setelah target melawan.',
      'Petugas berhasil menghentikanmu sebelum serangan berikutnya.',
      'Target berhasil bertahan dan membuatmu terdesak.',
      'Kamu tertangkap di lokasi setelah aksimu gagal.',
      'Seranganmu gagal karena target sudah menyadari keberadaanmu.',
      'Orang sekitar datang setelah mendengar keributan.',
      'Target berhasil menjauh dan kamu kehilangan kesempatan.',
      'Aksimu terbongkar sebelum serangan berhasil dilancarkan.',
      'Kamu gagal menyelesaikan serangan dan harus meninggalkan lokasi.'
    ]
  },
  rampok: {
    success: [
      'Kamu berhasil melewati penjagaan bank dan membawa kabur sebagian saldo target.',
      'Dengan perhitungan matang, kamu mengecoh penjaga dan keluar membawa hasil rampokan.',
      'Alarm terlambat berbunyi; kamu berhasil meninggalkan bank dengan jarahan.',
      'Kamu berhasil melewati bagian keamanan dan mengambil uang target.',
      'Penjagaan lengah sesaat dan kamu memanfaatkan kesempatan tersebut.',
      'Kamu berhasil keluar sebelum sistem keamanan mengunci seluruh pintu.',
      'Aksimu berjalan cepat hingga kamu berhasil membawa kabur uang.',
      'Penjaga terlambat menyadari keberadaanmu dan kamu berhasil melarikan diri.',
      'Kamu berhasil mendapatkan sebagian uang sebelum meninggalkan bank.',
      'Sistem keamanan gagal menghentikanmu dan kamu berhasil keluar.',
      'Kamu berhasil mengecoh penjaga dan membawa hasil rampokan.',
      'Alarm baru berbunyi setelah kamu berhasil meninggalkan gedung.',
      'Kamu menemukan celah keamanan dan berhasil mengambil uang target.',
      'Penjagaan teralihkan dan kamu berhasil memanfaatkan situasi.',
      'Kamu berhasil membawa uang keluar sebelum pintu otomatis terkunci.',
      'Aksimu berlangsung cepat dan penjaga tidak sempat menghentikanmu.',
      'Kamu berhasil keluar melalui jalur yang tidak terlalu dijaga.',
      'Penjaga kehilangan jejakmu saat kamu meninggalkan bank.',
      'Kamu berhasil mengambil uang dan segera meninggalkan lokasi.',
      'Alarm terlambat aktif sehingga kamu berhasil kabur.',
      'Kamu berhasil melewati pemeriksaan keamanan tanpa terdeteksi.',
      'Penjaga sibuk di bagian lain ketika kamu menjalankan aksimu.',
      'Kamu berhasil mengambil sebagian saldo target dan melarikan diri.',
      'Aksi berlangsung sesuai rencana sampai kamu keluar dari gedung.',
      'Kamu berhasil mengecoh sistem keamanan dan membawa uang pergi.',
      'Penjaga terlambat menyadari aksi hingga kamu sudah berada di luar.',
      'Kamu berhasil memanfaatkan pergantian penjaga untuk melancarkan aksi.',
      'Sistem keamanan sempat terganggu dan kamu berhasil menggunakannya.',
      'Kamu berhasil membawa kabur hasil rampokan sebelum pengejaran dimulai.',
      'Penjagaan tidak siap menghadapi aksimu dan kamu berhasil kabur.',
      'Kamu berhasil mengambil uang sebelum alarm aktif.',
      'Aksi berjalan mulus dan kamu berhasil meninggalkan bank.',
      'Kamu berhasil keluar dari gedung membawa sebagian uang target.',
      'Penjaga kehilangan beberapa detik penting dan kamu memanfaatkannya.',
      'Kamu berhasil melewati pintu keluar sebelum keamanan menutup akses.',
      'Alarm baru terdengar ketika kamu sudah cukup jauh dari lokasi.',
      'Kamu berhasil menjalankan aksi saat perhatian penjaga teralihkan.',
      'Sistem keamanan terlambat merespons dan kamu berhasil melarikan diri.',
      'Kamu berhasil mendapatkan uang lalu segera meninggalkan area.',
      'Penjaga gagal menghalangimu sebelum kamu mencapai pintu keluar.',
      'Kamu berhasil mengambil hasil rampokan dalam waktu singkat.',
      'Pergantian shift membuat penjagaan longgar dan kamu berhasil masuk.',
      'Kamu berhasil keluar membawa uang sebelum pengejaran dilakukan.',
      'Aksimu berhasil karena sistem keamanan mengalami gangguan.',
      'Kamu berhasil memanfaatkan celah penjagaan untuk mengambil uang.',
      'Penjaga tidak sempat bereaksi ketika kamu meninggalkan gedung.',
      'Kamu berhasil membawa hasil rampokan keluar dari bank.',
      'Alarm terlambat memberikan peringatan sehingga kamu berhasil kabur.',
      'Kamu berhasil melewati penjagaan dan meninggalkan lokasi dengan selamat.',
      'Uang target berhasil kamu bawa keluar sebelum bank mengunci akses.'
    ],
    failure: [
      'Penjaga bank membaca gerakanmu dan segera membunyikan alarm.',
      'Sistem keamanan bank mengunci akses sebelum kamu sempat mengambil uang.',
      'Penjaga berhasil menghentikan aksimu dan polisi segera datang.',
      'Alarm berbunyi tepat saat kamu mulai menjalankan aksimu.',
      'Sistem keamanan mendeteksi gerakanmu dan seluruh pintu terkunci.',
      'Penjaga menyadari keberadaanmu sebelum kamu mencapai area uang.',
      'Kamu gagal melewati pemeriksaan keamanan dan langsung dicurigai.',
      'Alarm aktif terlalu cepat sehingga rencanamu berantakan.',
      'Penjaga datang sebelum kamu berhasil mengambil uang target.',
      'Sistem keamanan mengunci ruangan dan membuatmu terjebak.',
      'Kamu salah memperkirakan jadwal penjagaan dan langsung ketahuan.',
      'Penjaga menemukanmu sebelum aksi berhasil dilakukan.',
      'Alarm berbunyi dan seluruh petugas langsung bergerak.',
      'Kamu gagal membuka akses menuju uang target.',
      'Sistem keamanan mengenali gerakanmu dan mengaktifkan penguncian.',
      'Penjaga menghadang jalan keluar sebelum kamu sempat kabur.',
      'Kamu tertangkap ketika mencoba membawa uang keluar.',
      'Aksimu diketahui kamera keamanan dan petugas segera datang.',
      'Pintu keluar terkunci sebelum kamu berhasil meninggalkan bank.',
      'Penjaga terlalu waspada sehingga kesempatanmu gagal.',
      'Kamu membuat kesalahan dan langsung memicu alarm.',
      'Sistem keamanan aktif ketika kamu baru mulai menjalankan aksi.',
      'Petugas berhasil mengepungmu sebelum kamu mendapatkan uang.',
      'Kamu gagal melewati penjagaan dan terpaksa melarikan diri.',
      'Alarm berbunyi setelah sistem mendeteksi keberadaanmu.',
      'Penjaga melihat gerakan mencurigakan dan menghampirimu.',
      'Kamu kehilangan kesempatan karena pintu keamanan terkunci.',
      'Petugas datang terlalu cepat dan menggagalkan aksimu.',
      'Sistem keamanan membuat semua akses menuju uang tertutup.',
      'Kamu tertangkap ketika mencoba keluar dari bank.',
      'Penjaga berhasil menemukan lokasi persembunyianmu.',
      'Alarm aktif sebelum kamu sempat membawa hasil rampokan.',
      'Kamu gagal mengecoh penjaga dan langsung dikejar.',
      'Sistem keamanan membaca pola gerakanmu dan mengunci gedung.',
      'Petugas berhasil menghentikanmu sebelum mengambil uang.',
      'Kamu salah memilih jalur keluar dan bertemu penjaga.',
      'Alarm membuat seluruh petugas berkumpul di lokasimu.',
      'Penjagaan diperketat tepat ketika kamu mulai beraksi.',
      'Kamu tidak sempat mengambil uang sebelum akses ditutup.',
      'Kamera keamanan menangkap gerakanmu dan petugas langsung datang.',
      'Penjaga berhasil menghadangmu di dekat pintu keluar.',
      'Sistem keamanan bekerja lebih cepat dari perkiraanmu.',
      'Kamu tertangkap setelah gagal melewati area penjagaan.',
      'Alarm berbunyi dan membuat semua rencana pelarianmu gagal.',
      'Penjaga menemukanmu sebelum kamu berhasil mencapai uang target.',
      'Kamu gagal membawa uang keluar karena semua akses dikunci.',
      'Petugas datang setelah melihat aktivitas mencurigakanmu.',
      'Aksimu berantakan ketika sistem keamanan tiba-tiba aktif.',
      'Kamu tertangkap di dalam bank sebelum berhasil membawa hasil rampokan.'
    ]
  },
  culik: {
    success: [
      'Kamu membawa target pergi sebelum ada yang sempat menghentikanmu.',
      'Target berhasil kamu sekap dan dibawa ke sel tahanan.',
      'Dengan rencana yang matang, target kini berada dalam tahananmu.',
      'Kamu berhasil membawa target pergi tanpa menarik perhatian.',
      'Target tidak sempat meminta bantuan sebelum kamu membawanya pergi.',
      'Kamu berhasil memindahkan target ke tempat persembunyian.',
      'Aksimu berlangsung cepat dan target berhasil kamu amankan.',
      'Kamu berhasil membawa target keluar sebelum ada yang menyadarinya.',
      'Target kini berada di tempat yang sudah kamu siapkan.',
      'Kamu berhasil menjauh dari lokasi bersama target.',
      'Tidak ada saksi yang menyadari saat kamu membawa target pergi.',
      'Kamu berhasil membuat target tidak sempat melawan.',
      'Aksimu berhasil dan target kini berada dalam tahananmu.',
      'Kamu berhasil membawa target meninggalkan lokasi.',
      'Target berhasil kamu amankan sebelum bantuan datang.',
      'Kamu memanfaatkan situasi sepi untuk membawa target pergi.',
      'Aksi berlangsung tanpa gangguan sampai target berada di tempat aman bagimu.',
      'Kamu berhasil memindahkan target ke lokasi tersembunyi.',
      'Target tidak sempat menghubungi siapa pun sebelum dibawa pergi.',
      'Kamu berhasil meninggalkan lokasi bersama target.',
      'Rencanamu berjalan lancar dan target berhasil kamu bawa.',
      'Kamu berhasil menguasai situasi dan membawa target pergi.',
      'Target berada dalam tahananmu sebelum orang sekitar menyadarinya.',
      'Kamu berhasil menjauh dari lokasi tanpa menarik perhatian.',
      'Aksi berlangsung cepat dan target tidak sempat meminta pertolongan.',
      'Kamu berhasil membawa target ke tempat persembunyian.',
      'Target berhasil kamu pindahkan sebelum ada yang datang.',
      'Kamu memanfaatkan jalan sepi untuk membawa target pergi.',
      'Tidak ada yang menyadari aksimu hingga kamu meninggalkan lokasi.',
      'Kamu berhasil membawa target keluar dari area tersebut.',
      'Target tidak sempat melakukan perlawanan berarti.',
      'Kamu berhasil menjalankan rencana dan membawa target pergi.',
      'Aksimu berhasil sebelum saksi sempat mengetahui kejadian.',
      'Target berhasil kamu tahan di lokasi yang sudah disiapkan.',
      'Kamu berhasil menghindari perhatian saat membawa target pergi.',
      'Target kini berada jauh dari lokasi awal.',
      'Kamu berhasil membawa target tanpa membuat keributan.',
      'Aksi berjalan sesuai rencana dan target berhasil diamankan.',
      'Kamu berhasil meninggalkan lokasi sebelum bantuan tiba.',
      'Target tidak sempat mencari pertolongan sebelum kamu pergi.',
      'Kamu berhasil memindahkan target ke tempat yang sulit ditemukan.',
      'Rencana berjalan lancar hingga target berada dalam tahananmu.',
      'Kamu berhasil membawa target pergi dari tempat semula.',
      'Tidak ada saksi yang cukup cepat menyadari kejadian.',
      'Kamu berhasil menyelesaikan aksi sebelum situasi berubah.',
      'Target berhasil kamu bawa dan kamu segera meninggalkan area.',
      'Kamu berhasil menghindari perhatian orang sekitar.',
      'Aksimu berlangsung cepat dan target tidak sempat kabur.',
      'Kamu berhasil membawa target ke lokasi persembunyian.',
      'Target kini berada dalam kendalimu setelah aksi berhasil.'
    ],
    failure: [
      'Rencana penculikanmu terbongkar dan polisi menangkapmu di lokasi.',
      'Target berhasil meminta bantuan; aksimu gagal sebelum sempat membawanya pergi.',
      'Saksi melihat kejadian itu dan polisi segera menggagalkan penculikan.',
      'Target berhasil melawan sebelum kamu sempat membawanya pergi.',
      'Orang sekitar menyadari kejadian dan langsung meminta bantuan.',
      'Kamu gagal membawa target karena seseorang datang tepat waktu.',
      'Target berteriak sehingga perhatian orang sekitar langsung tertuju padamu.',
      'Rencanamu diketahui sebelum target berhasil dibawa pergi.',
      'Polisi datang setelah menerima laporan dari saksi.',
      'Kamu kehilangan kesempatan ketika target berhasil melarikan diri.',
      'Saksi melihat gerakanmu dan segera menghubungi petugas.',
      'Target berhasil menghindar dan mencari tempat ramai.',
      'Kamu tertangkap sebelum berhasil membawa target keluar.',
      'Rencana berantakan setelah target berhasil meminta pertolongan.',
      'Orang sekitar menghalangi jalanmu sehingga aksi gagal.',
      'Target berhasil menarik perhatian orang lain.',
      'Kamu gagal menguasai situasi dan target berhasil kabur.',
      'Polisi datang sebelum kamu sempat meninggalkan lokasi.',
      'Saksi melihat kejadian dan langsung mengejarmu.',
      'Target berhasil melawan dan membuat rencanamu gagal.',
      'Kamu kehilangan kendali setelah orang-orang mulai berdatangan.',
      'Aksimu diketahui sebelum target berhasil dipindahkan.',
      'Target berhasil berteriak dan membuat suasana menjadi ramai.',
      'Kamu tertangkap ketika mencoba membawa target pergi.',
      'Seseorang melihat kejadian dari kejauhan dan memanggil bantuan.',
      'Target berhasil melepaskan diri sebelum dibawa pergi.',
      'Polisi tiba terlalu cepat dan menggagalkan rencanamu.',
      'Kamu salah memilih lokasi sehingga banyak orang melihat aksimu.',
      'Target berhasil meminta bantuan melalui telepon.',
      'Saksi berhasil mengingat ciri-cirimu dan melaporkan kejadian.',
      'Kamu gagal membawa target karena jalan keluar sudah ramai.',
      'Orang sekitar langsung mengejar setelah menyadari kejadian.',
      'Target berhasil melarikan diri ketika perhatianmu teralihkan.',
      'Rencanamu terbongkar sebelum aksi dimulai.',
      'Kamu terpaksa meninggalkan target setelah mendengar sirene.',
      'Polisi mengepung lokasi sebelum kamu berhasil pergi.',
      'Target berhasil melawan dan menarik perhatian banyak orang.',
      'Kamu kehilangan kesempatan setelah seorang saksi datang.',
      'Aksi gagal karena target sudah menyadari niatmu.',
      'Kamu tertangkap saat mencoba membawa target ke kendaraan.',
      'Saksi melihat kejadian dan segera meminta pertolongan.',
      'Target berhasil kabur sebelum kamu sempat mengamankannya.',
      'Orang-orang mulai berdatangan setelah mendengar keributan.',
      'Polisi tiba sebelum kamu berhasil meninggalkan tempat.',
      'Rencana gagal ketika target berhasil menarik perhatian warga.',
      'Kamu tidak sempat membawa target pergi karena aksimu ketahuan.',
      'Target berhasil menghindar dan mencari bantuan.',
      'Aksimu terbongkar dan kamu terpaksa meninggalkan lokasi.',
      'Kamu tertangkap setelah gagal membawa target keluar.'
    ]
  },
  jarah: {
    success: [
      'Kamu masuk tanpa diketahui dan membawa satu furniture dari rumah target.',
      'Saat rumah kosong, satu furniture berhasil kamu angkut.',
      'Kamu berhasil membawa furniture pilihan sebelum pemilik rumah kembali.',
      'Rumah dalam keadaan sepi dan kamu berhasil mengambil furniture.',
      'Kamu menemukan rumah kosong dan berhasil membawa satu barang.',
      'Pemilik sedang pergi sehingga kamu berhasil mengambil furniture target.',
      'Kamu berhasil keluar membawa furniture sebelum ada yang menyadari.',
      'Aksimu berlangsung cepat dan satu furniture berhasil kamu bawa.',
      'Kamu memanfaatkan rumah yang kosong untuk mengambil barang.',
      'Furniture target berhasil kamu bawa keluar tanpa diketahui.',
      'Kamu berhasil mengambil satu furniture saat tidak ada orang di rumah.',
      'Pemilik belum kembali ketika kamu berhasil meninggalkan lokasi.',
      'Kamu menemukan kesempatan dan berhasil membawa furniture pilihan.',
      'Aksimu berjalan lancar hingga furniture berhasil dibawa pergi.',
      'Kamu berhasil masuk dan keluar sambil membawa satu furniture.',
      'Rumah target sepi sehingga aksimu berjalan tanpa gangguan.',
      'Kamu berhasil membawa furniture sebelum pemilik menyadari kehilangan.',
      'Tidak ada orang di sekitar saat kamu mengambil furniture target.',
      'Kamu berhasil mengangkut satu furniture dan segera meninggalkan lokasi.',
      'Pemilik rumah sedang pergi dan kamu memanfaatkan kesempatan tersebut.',
      'Aksi berlangsung cepat hingga furniture berhasil dibawa keluar.',
      'Kamu berhasil mengambil barang dari rumah target tanpa diketahui.',
      'Furniture pilihan berhasil kamu angkut sebelum ada yang datang.',
      'Kamu menemukan rumah kosong dan berhasil membawa hasil jarahan.',
      'Pemilik belum pulang sehingga kamu berhasil menjalankan aksimu.',
      'Kamu berhasil mengambil furniture dan meninggalkan rumah dengan tenang.',
      'Aksimu selesai sebelum siapa pun menyadari keberadaanmu.',
      'Kamu berhasil membawa satu furniture dari rumah yang sedang kosong.',
      'Rumah target tidak berpenghuni sementara dan kamu memanfaatkan situasi.',
      'Kamu berhasil mengeluarkan furniture sebelum ada gangguan.',
      'Furniture berhasil dibawa pergi tanpa menarik perhatian.',
      'Kamu berhasil memanfaatkan waktu ketika pemilik rumah sedang keluar.',
      'Aksi berlangsung singkat dan furniture berhasil kamu amankan.',
      'Kamu berhasil mengambil satu furniture lalu meninggalkan area.',
      'Pemilik rumah tidak menyadari apa pun sampai kamu sudah pergi.',
      'Kamu berhasil membawa furniture keluar melalui jalur yang sepi.',
      'Rumah dalam kondisi tenang sehingga aksimu berhasil.',
      'Kamu berhasil memindahkan furniture tanpa diketahui siapa pun.',
      'Furniture target berhasil kamu bawa sebelum rumah kembali ramai.',
      'Kamu berhasil masuk ketika rumah sedang kosong.',
      'Aksimu berjalan lancar dan furniture berhasil dibawa pergi.',
      'Kamu berhasil mengambil furniture pilihan tanpa menimbulkan keributan.',
      'Tidak ada saksi yang melihat saat kamu membawa furniture keluar.',
      'Kamu berhasil meninggalkan rumah sebelum pemilik kembali.',
      'Furniture berhasil kamu angkut dalam waktu singkat.',
      'Kamu memanfaatkan rumah yang kosong dan berhasil mengambil barang.',
      'Aksi berhasil dilakukan sebelum ada orang yang datang.',
      'Kamu berhasil membawa furniture target keluar dari rumah.',
      'Pemilik sedang tidak berada di tempat saat kamu menjalankan aksi.',
      'Kamu berhasil mengamankan furniture sebelum meninggalkan lokasi.'
    ],
    failure: [
      'Aksimu diketahui sebelum berhasil membawa furniture apa pun.',
      'Pemilik rumah menyadari kehadiranmu dan rencanamu berantakan.',
      'Kamu tertangkap saat mencoba membawa furniture keluar.',
      'Pemilik tiba-tiba pulang dan langsung mengetahui aksimu.',
      'Seorang tetangga melihatmu membawa furniture dari rumah target.',
      'Kamu gagal mengangkat furniture sebelum ada yang datang.',
      'Pemilik rumah mendengar suara dan segera memeriksa ruangan.',
      'Aksimu terbongkar sebelum furniture berhasil dipindahkan.',
      'Kamu kehilangan kesempatan ketika pemilik tiba-tiba muncul.',
      'Tetangga melihat gerakan mencurigakan dan memanggil pemilik.',
      'Furniture terlalu berat dan membuat aksimu gagal.',
      'Kamu membuat suara keras sehingga orang sekitar menyadarinya.',
      'Pemilik rumah kembali lebih cepat dari perkiraanmu.',
      'Kamu tertangkap saat mencoba melewati pintu keluar.',
      'Saksi melihatmu membawa furniture dan langsung mengejar.',
      'Aksimu gagal setelah rumah mendadak menjadi ramai.',
      'Kamu tidak sempat membawa furniture karena pemilik sudah pulang.',
      'Tetangga curiga melihat aktivitasmu dan langsung mendekat.',
      'Pemilik menyadari ada yang aneh sebelum kamu berhasil pergi.',
      'Furniture terjatuh dan menimbulkan suara keras.',
      'Kamu gagal mengeluarkan furniture dari rumah.',
      'Seseorang melihatmu dari luar rumah dan memanggil bantuan.',
      'Pemilik datang tepat saat furniture hendak dibawa pergi.',
      'Aksimu diketahui sebelum barang berhasil melewati pintu.',
      'Kamu salah memperkirakan rumah dalam keadaan kosong.',
      'Tetangga mendengar suara dan membuatmu kehilangan kesempatan.',
      'Pemilik berhasil menghentikanmu sebelum furniture dibawa pergi.',
      'Kamu tertangkap ketika mencoba mengangkat furniture.',
      'Rumah ternyata memiliki orang lain di dalam dan aksimu gagal.',
      'Kamu membuat terlalu banyak suara saat memindahkan barang.',
      'Saksi melihatmu masuk dan segera memberi tahu pemilik.',
      'Pemilik pulang saat kamu masih berada di dalam rumah.',
      'Kamu gagal membawa furniture karena jalur keluar terhalang.',
      'Aksi terbongkar setelah furniture menabrak sesuatu.',
      'Tetangga datang setelah melihat aktivitas mencurigakan.',
      'Kamu terpaksa meninggalkan furniture setelah mendengar suara pemilik.',
      'Pemilik mengetahui kehilangan sebelum kamu berhasil pergi.',
      'Kamu gagal keluar karena pintu rumah terkunci.',
      'Saksi berhasil melihat wajahmu saat membawa furniture.',
      'Pemilik mendadak kembali dan membuatmu panik.',
      'Furniture tidak bisa dipindahkan tepat waktu sebelum ada yang datang.',
      'Aksimu gagal karena rumah ternyata tidak benar-benar kosong.',
      'Kamu tertangkap setelah mencoba membawa furniture melewati halaman.',
      'Tetangga memergokimu dan langsung meminta bantuan.',
      'Pemilik berhasil menghentikanmu sebelum barang keluar rumah.',
      'Kamu gagal membawa furniture karena suara langkah kaki mendekat.',
      'Aksimu terbongkar saat mencoba membuka jalan keluar.',
      'Seseorang melihatmu dari jendela dan segera memanggil pemilik.',
      'Kamu terpaksa meninggalkan furniture setelah diketahui warga.'
    ]
  }
})

export function getRpgCrimeStory(action, result) {
  const stories = CRIME_STORIES[action]?.[result]
  if (!stories) throw new Error(`Cerita kriminal tidak ditemukan: ${action}/${result}`)
  return stories[Math.floor(Math.random() * stories.length)]
}
